### ISSUE TITLE
run it with Java 1.8.0_181 throws java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension

### ISSUE THREAD

**Issue by tapifolti** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#106]
I upgraded to Java 1.8.0_181 
has gradle as:
    compile "mysql:mysql-connector-java:8.0.12"
    compile "com.google.cloud.sql:mysql-socket-factory-connector-j-8:1.0.11"
and got this:
java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1087)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:576)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:372)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:493)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStreamUser(GoogleCredential.java:815)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:257)
	at com.google.api.client.googleapis.auth.oauth2.DefaultCredentialProvider.getCredentialUsingWellKnownFile(DefaultCredentialProvider.java:249)
	at com.google.api.client.googleapis.auth.oauth2.DefaultCredentialProvider.getDefaultCredentialUnsynchronized(DefaultCredentialProvider.java:117)
	at com.google.api.client.googleapis.auth.oauth2.DefaultCredentialProvider.getDefaultCredential(DefaultCredentialProvider.java:91)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:213)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:191)
	at com.google.cloud.sql.core.SslSocketFactory$ApplicationDefaultCredentialFactory.create(SslSocketFactory.java:598)
	at com.google.cloud.sql.core.SslSocketFactory.getInstance(SslSocketFactory.java:147)
	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:75)
	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:40)

Found explanation as: https://bugs.java.com/view_bug.do?bug_id=JDK-8156502

**Comment by tapifolti** [comment]
it was caused by the jetty-alpn-boot/alpn-boot-8.1.11.v20170118.jar on classpath, without that it works fine
