### ISSUE TITLE
ClassCastException when using IAM with Google OAuth Client

### ISSUE THREAD

**Issue by dirkluijk** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1093]
## Bug Description

When using the Google OAuth Client with this library (a combination that is currently used in Spring Cloud GCP), the following error occurs:

```
Caused by: java.lang.ClassCastException: class com.google.api.client.googleapis.auth.oauth2.GoogleCredential cannot be cast to class com.google.auth.http.HttpCredentialsAdapter (com.google.api.client.googleapis.auth.oauth2.GoogleCredential and com.google.auth.http.HttpCredentialsAdapter are in unnamed module of loader 'app')
```

## Example code + How to reproduce

https://github.com/dirkluijk/spring-gcp-sql-issue

Just make sure to set the `encoded-key` in `application.yaml` to a valid base64-encoded key and run the application.

## Stacktrace
```
java.lang.ClassCastException: class com.google.api.client.googleapis.auth.oauth2.GoogleCredential cannot be cast to class com.google.auth.http.HttpCredentialsAdapter (com.google.api.client.googleapis.auth.oauth2.GoogleCredential and com.google.auth.http.HttpCredentialsAdapter are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @6e8f2094)
	at com.google.cloud.sql.core.CloudSqlInstance.<init>(CloudSqlInstance.java:156)
```

## Environment

1. OS type and version: Mac OS
2. Java SDK version: 17
2. Socket Factory version: 1.8.0

## Related tickets

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1346

**Comment by kurtisvg** [comment]
Hey @dirkluijk -- thanks for opening an issue, and being thorough enough to provide a minimal repro. At first glance, it looks like this is actually a problem in the spring-cloud-gcp starter (which I see you've linked an issue for). Let me loop them in on this issue as well. 

My understanding is that Google Oauth2 Library is deprecated, and that google-auth-library is the [preferred replacement.](https://github.com/googleapis/google-auth-library-java).

@meltsufin -- Can you help us out here?

@enocom FYI

**Comment by meltsufin** [comment]
@JoeWang1127 Can you please take a look, since you worked on this issue before but needed a repro? Thanks!

**Comment by JoeWang1127** [comment]
> @JoeWang1127 Can you please take a look, since you worked on this issue before but needed a repro? Thanks!

Sure, will do.

**Comment by vy** [comment]
I can reproduce the problem using the provided sample project.:

```
Caused by: java.lang.ClassCastException: class com.google.api.client.googleapis.auth.oauth2.GoogleCredential cannot be cast to class com.google.auth.http.HttpCredentialsAdapter (com.google.api.client.googleapis.auth.oauth2.GoogleCredential and com.google.auth.http.HttpCredentialsAdapter are in unnamed module of loader 'app')
	at com.google.cloud.sql.core.CloudSqlInstance.<init>(CloudSqlInstance.java:156) ~[jdbc-socket-factory-core-1.7.0.jar:na]
	at com.google.cloud.sql.core.CoreSocketFactory.lambda$getCloudSqlInstance$0(CoreSocketFactory.java:158) ~[jdbc-socket-factory-core-1.7.0.jar:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at com.google.cloud.sql.core.CoreSocketFactory.getCloudSqlInstance(CoreSocketFactory.java:156) ~[jdbc-socket-factory-core-1.7.0.jar:na]
	at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:291) ~[jdbc-socket-factory-core-1.7.0.jar:na]
	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:252) ~[jdbc-socket-factory-core-1.7.0.jar:na]
	at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:76) ~[postgres-socket-factory-1.7.0.jar:na]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:229) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.3.8.jar:42.3.8]
```

Note that this is identical to the one shared in GoogleCloudPlatform/spring-cloud-gcp#1346.

**Comment by dirkluijk** [comment]
I am not sure if this is an issue with `spring-cloud-gcp`, since the class casting is done in this library.

In `CloudSqlInstance`, I tried changing:
```java
HttpCredentialsAdapter credentialsAdapter = (HttpCredentialsAdapter) tokenSourceFactory.create();
this.credentials = Optional.of((OAuth2Credentials) credentialsAdapter.getCredentials());
```
to:
```java
if (source instanceof HttpCredentialsAdapter) {
  HttpCredentialsAdapter adapter = (HttpCredentialsAdapter) source;
  this.credentials = Optional.of((OAuth2Credentials) adapter.getCredentials());
} else if (source instanceof Credential) {
  Credential credential = (Credential) source;
  GoogleCredentials googleCredentials = new GoogleCredentials(
          new AccessToken(
                  credential.getAccessToken(),
                  new Date(credential.getExpirationTimeMilliseconds())
          )
  );
  this.credentials = Optional.of(googleCredentials);
} else {
  throw new RuntimeException("Not supporting credentials of type " + source.getClass().getName());
}
```
This fixed the casting issue and makes it more acceptable. However, this causes a new issue:
```
OAuth2Credentials instance does not support refreshing the access token.
```
which is caused - again - by `CloudSqlInstance` that assumes a refreshable credential.

**Comment by dirkluijk** [comment]
This fixed the issue for me: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1097.

Not sure what you think of the solution, let me know.

**Comment by dirkluijk** [comment]
Fix worked fine with my "application default" credentials, however, I overlooked the fact that the expiration time can be `null` (which was the case in our production environment). Fixed this in https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1117.
