### ISSUE TITLE
working with mysql socket and iam auth at the same time 

### ISSUE THREAD

**Issue by hanfi** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1189]
### Bug Description

hi i'm using mysql-socket-factory-connector-j-8 to connect a cloud run container to Mysql cloud sql instance.

a lot of options are available to do it, but the one i need to make it work is : 

- cloud run has Cloud SQL connections enabled (this creates some kind of a cloud sql proxy side car container that shares a socket in /cloudsql/INSTANCE_ID that can be used from your cloud run container [link to documentation](https://cloud.google.com/sql/docs/mysql/connect-run?_ga=2.40665698.-1100797918.1668437632&_gac=1.185697115.1676974444.CjwKCAiA9NGfBhBvEiwAq5vSy0PaHBu7zPG4FX_efXZ0Yalgkj8mzPI9FJhMBWFrNXN4SxX4a1J2nxoC03kQAvD_BwE&hl=fr)
-  using enableIamAuth=true to connect using Service account

each one of those set ups works alone but together i got this error  : `SSL connection required for plugin "mysql_clear_password". Check if 'sslMode' is enabled.`

### Example code (or command)

```Java
- working jdbc string with cloud run sql connection feature eanbled and using socket: 

jdbc:mysql:///<databaseName>?cloudSqlInstance=<project>:<region>:<dbname>&socketFactory=com.google.cloud.sql.mysql.SocketFactory&=true&ipTypes=PRIVATE&unixSocketPath=/cloudsql/<project>:<region>:<dbname>

- also working jdbc string without socket but with iamAuth enabled :

jdbc:mysql:///<databaseName>?cloudSqlInstance=<project>:<region>:<dbname>&socketFactory=com.google.cloud.sql.mysql.SocketFactory&ipTypes=PRIVATE&enableIamAuth=true

- not working jdbc string when both enableIamAuth and unixSocketPath are used : 
jdbc:mysql:///<databaseName>?cloudSqlInstance=<project>:<region>:<dbname>&socketFactory=com.google.cloud.sql.mysql.SocketFactory&&enableIamAuth=true&ipTypes=PRIVATE&unixSocketPath=/cloudsql/<project>:<region>:<dbname>
```

### Stacktrace

```bash
2023-03-01 17:18:13 2023-03-01 17:18:13,993 INFO  [com.goo.clo.sql.cor.CoreSocketFactory] (agroal-11) Connecting to Cloud SQL instance [mystic-aileron-190912:europe-west9:test-shi] via unix socket at /cloudsql/mystic-aileron-190912:europe-west9:test-shi.
2023-03-01 17:18:14 2023-03-01 17:18:14,005 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': SSL connection required for plugin "mysql_clear_password". Check if 'sslMode' is enabled.
2023-03-01 17:18:14 2023-03-01 17:18:14,005 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) SQL Error: 0, SQLState: S1000
2023-03-01 17:18:14 2023-03-01 17:18:14,005 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (executor-thread-0) SSL connection required for plugin "mysql_clear_password". Check if 'sslMode' is enabled.
2023-03-01 17:18:14 2023-03-01 17:18:14,006 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /v1/users failed, error id: fcf176b4-bab3-4a53-8410-bf0c85fc1e49-2: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
2023-03-01 17:18:14 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
2023-03-01 17:18:14 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
2023-03-01 17:18:14 	at org.hibernate.query.Query.getResultList(Query.java:165)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:269)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:149)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.list(JpaOperations.java:24)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.list(JpaOperations.java:10)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.listAll(AbstractJpaOperations.java:305)
2023-03-01 17:18:14 	at org.acme.repository.UserRepository.listAll(UserRepository.java)
2023-03-01 17:18:14 	at org.acme.repository.UserRepository_ClientProxy.listAll(Unknown Source)
2023-03-01 17:18:14 	at org.acme.service.impl.DefaultUserService.getAllUsers(DefaultUserService.java:30)
2023-03-01 17:18:14 	at org.acme.service.impl.DefaultUserService_ClientProxy.getAllUsers(Unknown Source)
2023-03-01 17:18:14 	at org.acme.controller.UserController.getUsers(UserController.java:40)
2023-03-01 17:18:14 	at org.acme.controller.UserController_ClientProxy.getUsers(Unknown Source)
2023-03-01 17:18:14 	at org.acme.controller.UserController$quarkusrestinvoker$getUsers_4b9221263c4fb1e6e88448a563d3364eb951551a.invoke(Unknown Source)
2023-03-01 17:18:14 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2023-03-01 17:18:14 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
2023-03-01 17:18:14 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2023-03-01 17:18:14 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2023-03-01 17:18:14 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2023-03-01 17:18:14 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2023-03-01 17:18:14 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-03-01 17:18:14 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-03-01 17:18:14 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-01 17:18:14 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-01 17:18:14 Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
2023-03-01 17:18:14 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
2023-03-01 17:18:14 	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
2023-03-01 17:18:14 	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doQuery(Loader.java:956)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doList(Loader.java:2868)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doList(Loader.java:2850)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.list(Loader.java:2677)
2023-03-01 17:18:14 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
2023-03-01 17:18:14 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
2023-03-01 17:18:14 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218)
2023-03-01 17:18:14 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
2023-03-01 17:18:14 	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
2023-03-01 17:18:14 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
2023-03-01 17:18:14 	... 23 more
2023-03-01 17:18:14 Caused by: java.sql.SQLException: SSL connection required for plugin "mysql_clear_password". Check if 'sslMode' is enabled.
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
2023-03-01 17:18:14 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
2023-03-01 17:18:14 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
2023-03-01 17:18:14 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
2023-03-01 17:18:14 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-03-01 17:18:14 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
2023-03-01 17:18:14 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
2023-03-01 17:18:14 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-03-01 17:18:14 	... 1 more
2023-03-01 17:18:14 2023-03-01 17:18:14,007 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
2023-03-01 17:18:14 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
2023-03-01 17:18:14 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
2023-03-01 17:18:14 	at org.hibernate.query.Query.getResultList(Query.java:165)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:269)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.list(PanacheQueryImpl.java:149)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.list(JpaOperations.java:24)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.list(JpaOperations.java:10)
2023-03-01 17:18:14 	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.listAll(AbstractJpaOperations.java:305)
2023-03-01 17:18:14 	at org.acme.repository.UserRepository.listAll(UserRepository.java)
2023-03-01 17:18:14 	at org.acme.repository.UserRepository_ClientProxy.listAll(Unknown Source)
2023-03-01 17:18:14 	at org.acme.service.impl.DefaultUserService.getAllUsers(DefaultUserService.java:30)
2023-03-01 17:18:14 	at org.acme.service.impl.DefaultUserService_ClientProxy.getAllUsers(Unknown Source)
2023-03-01 17:18:14 	at org.acme.controller.UserController.getUsers(UserController.java:40)
2023-03-01 17:18:14 	at org.acme.controller.UserController_ClientProxy.getUsers(Unknown Source)
2023-03-01 17:18:14 	at org.acme.controller.UserController$quarkusrestinvoker$getUsers_4b9221263c4fb1e6e88448a563d3364eb951551a.invoke(Unknown Source)
2023-03-01 17:18:14 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2023-03-01 17:18:14 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
2023-03-01 17:18:14 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
2023-03-01 17:18:14 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2023-03-01 17:18:14 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2023-03-01 17:18:14 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2023-03-01 17:18:14 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-03-01 17:18:14 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-03-01 17:18:14 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-01 17:18:14 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-01 17:18:14 Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
2023-03-01 17:18:14 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
2023-03-01 17:18:14 	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)
2023-03-01 17:18:14 	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
2023-03-01 17:18:14 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doQuery(Loader.java:956)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doList(Loader.java:2868)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.doList(Loader.java:2850)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
2023-03-01 17:18:14 	at org.hibernate.loader.Loader.list(Loader.java:2677)
2023-03-01 17:18:14 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
2023-03-01 17:18:14 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
2023-03-01 17:18:14 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:218)
2023-03-01 17:18:14 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
2023-03-01 17:18:14 	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
2023-03-01 17:18:14 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
2023-03-01 17:18:14 	... 23 more
2023-03-01 17:18:14 Caused by: java.sql.SQLException: SSL connection required for plugin "mysql_clear_password". Check if 'sslMode' is enabled.
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
2023-03-01 17:18:14 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
2023-03-01 17:18:14 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
2023-03-01 17:18:14 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
2023-03-01 17:18:14 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
2023-03-01 17:18:14 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-03-01 17:18:14 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
2023-03-01 17:18:14 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
2023-03-01 17:18:14 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-03-01 17:18:14 	... 1 more
```

### Steps to reproduce?

1. enable sql connection feature in cloud run 
2. enable IAM-auth in cloud sql and create SA and grant acces to your DB
3. set your jdbc string with unixSocketPath + enableIamAuth 

### Environment

1. OS type and version: registry.access.redhat.com/ubi8/openjdk-11:1.14
2. Java SDK version: registry.access.redhat.com/ubi8/openjdk-11:1.14
3. Cloud SQL Java Socket Factory version:  mysql-socket-factory-connector-j-8 1.10.0

### Additional Details

tested with sslMode=REQUIRED and sslMode=DISABLED both doesn't work

**Comment by shubha-rajan** [comment]
Hi @hanfi. Unfortunately, using automatic IAM auth in Unix socket mode is not supported. 

However, when using the Java Connector with Cloud Run, you typically don't need to use the socket. The socket provided by Cloud Run is actually an integrated version of the Cloud SQL Proxy, and is meant to be used when deploying applications in languages that don't have connector libraries like this one.

My suggestion would be to disable the Cloud SQL integration on the cloud run instance and use the connector without the socket.
