### ISSUE TITLE
IllegalAccessError when using gradle nativeCompile

### ISSUE THREAD

**Issue by andreldsr** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1268]
### Bug Description

While trying to build a spring boot 3 project with kotlin and gradle with a connection to Postgres SQL on GCP i receive this error 
```
Fatal error: java.lang.IllegalAccessError: class com.google.cloud.sql.nativeimage.CloudSqlFeature (in unnamed module @0x5831989d) cannot access class com.oracle.svm.core.configure.ResourcesRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.configure to unnamed module @0x5831989d
        at com.google.cloud.sql.nativeimage.CloudSqlFeature.beforeAnalysis(CloudSqlFeature.java:55)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
    at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
```

### Example code (or command)

```Java
id("org.graalvm.buildtools.native") version "0.9.20"
implementation("com.google.cloud.sql:postgres-socket-factory:1.11.1")
```

### Steps to reproduce?

The project runs and connects normally but when I run ./gradlew nativeCompile it crashes

### Environment

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4 (GraalVM Community 17.0.4+8-jvmci-22.2-b06)
OS:           Linux 5.14.0-1054-oem amd64

**Comment by enocom** [comment]
Thanks for the report @andreldsr. I'm a bit surprised to hear this as we shipped GraalVM support awhile ago. I'll look into it.

**Comment by enocom** [comment]
Related: https://github.com/oracle/graal/pull/3803.

**Comment by enocom** [comment]
@andreldsr Have you tried this on a more recent version of the GraalVM (e.g. 22.3)?

**Comment by andreldsr** [comment]
Actually I've started using this enviroment

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (GraalVM Community 17.0.5+8-jvmci-22.3-b08)
OS:           Linux 5.14.0-1054-oem amd64

I can run the ./gradlew bootBuildImage but cant run the ./gradlew nativeCompile

**Comment by andreldsr** [comment]
Here is the repository, if you'd like to look for any misconfiguration or something like that 
https://github.com/andreldsr/cartinhas

**Comment by enocom** [comment]
Thanks for the reproduction. I'll take a look.

**Comment by enocom** [comment]
If I comment out this line in your `build.gradle.kts`, the native compilation works:

```
mavenBom("com.google.cloud:spring-cloud-gcp-dependencies:$springCloudGcpVersion")
```

Meanwhile, if I build a minimal Spring app with the Socket Factory, I also get no compilation error. This seems to be some kind of conflict with the above above.

**Comment by enocom** [comment]
Feel free to open with more information if you think there’s a problem here.
