### ISSUE TITLE
Update dependency com.google.auth:google-auth-library-oauth2-http to v1.16.0

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1294]
### Feature Description

This library cannot be automatically upgraded because it changes the behavior of the oauth2 token refresh. We need to refactor the token refresh cycle to upgrade this library.

**Comment by enocom** [comment]
Current tests are failing with this exception:

```
java.lang.RuntimeException: An exception occurred while fetching IAM auth token:
[1321](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1322)
	at com.google.cloud.sql.core.SqlAdminApiFetcher.addExceptionContext(SqlAdminApiFetcher.java:333)
[1322](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1323)
	at com.google.cloud.sql.core.SqlAdminApiFetcher.fetchEphemeralCertificate(SqlAdminApiFetcher.java:240)
[1323](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1324)
	at com.google.cloud.sql.core.SqlAdminApiFetcher.lambda$getInstanceData$1(SqlAdminApiFetcher.java:133)
[1324](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1325)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
[1325](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1326)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
[1326](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1327)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
[1327](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1328)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[1328](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1329)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[1329](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1330)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[1330](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1331)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[1331](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1332)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[1332](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1333)
	at java.base/java.lang.Thread.run(Thread.java:833)
[1333](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1334)
Caused by: java.io.IOException: Error requesting access token
[1334](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1335)
	at com.google.auth.oauth2.ImpersonatedCredentials.refreshAccessToken(ImpersonatedCredentials.java:511)
[1335](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1336)
	at com.google.auth.oauth2.ExternalAccountCredentials.exchangeExternalCredentialForAccessToken(ExternalAccountCredentials.java:479)
[1336](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1337)
	at com.google.auth.oauth2.IdentityPoolCredentials.refreshAccessToken(IdentityPoolCredentials.java:179)
[1337](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1338)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269)
[1338](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1339)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
[1339](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1340)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[1340](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1341)
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
[1341](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1342)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
[1342](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1343)
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581)
[1343](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1344)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:192)
[1344](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1345)
	at com.google.cloud.sql.core.SqlAdminApiFetcher.fetchEphemeralCertificate(SqlAdminApiFetcher.java:234)
[1345](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1346)
	... 10 more
[1346](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1347)
Caused by: com.google.api.client.http.HttpResponseException: 403 Forbidden
[1347](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1348)
POST https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/***:generateAccessToken
[1348](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1349)
{
[1349](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1350)
  "error": {
[1350](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1351)
    "code": 403,
[1351](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1352)
    "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
[1352](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1353)
    "errors": [
[1353](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1354)
      {
[1354](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1355)
        "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
[1355](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1356)
        "domain": "global",
[1356](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1357)
        "reason": "forbidden"
[1357](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1358)
      }
[1358](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1359)
    ],
[1359](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1360)
    "status": "PERMISSION_DENIED",
[1360](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1361)
    "details": [
[1361](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1362)
      {
[1362](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1363)
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
[1363](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1364)
        "reason": "IAM_PERMISSION_DENIED",
[1364](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1365)
        "domain": "iam.googleapis.com",
[1365](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1366)
        "metadata": {
[1366](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1367)
          "permission": "iam.serviceAccounts.getAccessToken"
[1367](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1368)
        }
[1368](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1369)
      }
[1369](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1370)
    ]
[1370](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1371)
  }
[1371](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1372)
}
[1372](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4493778046/jobs/7905416659?pr=1078#step:7:1373)
```

What about that makes you think it's a Java 8 vs Java 9 problem?
