### ISSUE TITLE
Connection hung at `First Cloud SQL connection, generating RSA key pair`

### ISSUE THREAD

**Issue by depsypher** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1317]
### Question

I'm seeing the same behavior as described in Issue #148 and am not sure what's causing it.

Logs show this, then app hangs for as long as I let it run (so far just 5-10 min before I just terminate it):
`INFO: First Cloud SQL connection, generating RSA key pair.`

I can step into getInstanceData() and see it not returning. I've tried updating guava (to 32.0.0-jre) and postgres-socket-factory (to 1.11.2), and using different versions of postgres drivers, but no luck. I'm connecting via a jdbc uri passed to DBCP which hangs when doing a basic `DriverManager.getConnection(this._connectUri, this._props)` from java.sql. Using java 8 btw.

Not sure where else to look for the source of the problem. Hopefully it's something silly or simple I'm just missing somewhere. This was working at some point in the past, but it's hard to say what changed in my app or dependencies to break it.

**Comment by enocom** [comment]
@depsypher Thanks for the question.

What version are you using?

**Comment by depsypher** [comment]
On v1.11.2 I'm able to step through to here where it hangs for at least ten minutes maybe longer (or forever). I took this thread dump. I'm able to connect to this database in IntelliJ's database editor, so not sure why my code is having issues. I was on v1.7.0 before and it hung in the same place.

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.security.provider.DigestBase.engineDigest(DigestBase.java:209)
	  at sun.security.provider.DigestBase.engineDigest(DigestBase.java:186)
	  at java.security.MessageDigest$Delegate.engineDigest(MessageDigest.java:617)
	  at java.security.MessageDigest.digest(MessageDigest.java:368)
	  at java.security.MessageDigest.digest(MessageDigest.java:414)
	  at com.sun.crypto.provider.PKCS12PBECipherCore.derive(PKCS12PBECipherCore.java:118)
	  at com.sun.crypto.provider.PKCS12PBECipherCore.derive(PKCS12PBECipherCore.java:68)
	  at com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:338)
	  at com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:376)
	  at com.sun.crypto.provider.PKCS12PBECipherCore.implInit(PKCS12PBECipherCore.java:361)
	  at com.sun.crypto.provider.PKCS12PBECipherCore$PBEWithSHA1AndRC2_40.engineInit(PKCS12PBECipherCore.java:545)
	  at javax.crypto.Cipher.implInit(Cipher.java:813)
	  at javax.crypto.Cipher.chooseProvider(Cipher.java:867)
	  - locked <0x2116> (a java.lang.Object)
	  at javax.crypto.Cipher.init(Cipher.java:1542)
	  at javax.crypto.Cipher.init(Cipher.java:1473)
	  at sun.security.pkcs12.PKCS12KeyStore.lambda$engineLoad$1(PKCS12KeyStore.java:2074)
	  at sun.security.pkcs12.PKCS12KeyStore$$Lambda$412.1906464391.tryOnce(Unknown Source:-1)
	  at sun.security.pkcs12.PKCS12KeyStore$RetryWithZero.run(PKCS12KeyStore.java:285)
	  at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2069)
	  - locked <0x2117> (a sun.security.pkcs12.PKCS12KeyStore)
	  at java.security.KeyStore.load(KeyStore.java:1445)
	  at com.google.api.client.util.SecurityUtils.loadKeyStore(SecurityUtils.java:80)
	  at com.google.api.client.googleapis.GoogleUtils.getCertificateTrustStore(GoogleUtils.java:86)
	  - locked <0x1123> (a java.lang.Class)
	  at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:87)
	  at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:58)
	  at com.google.cloud.sql.SqlAdminApiFetcherFactory.create(SqlAdminApiFetcherFactory.java:54)
	  at com.google.cloud.sql.core.CoreSocketFactory.getInstance(CoreSocketFactory.java:105)
	  - locked <0x20e2> (a java.lang.Class)
	  at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:201)
	  at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:77)
	  at org.postgresql.core.PGStream.createSocket(PGStream.java:226)
	  at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	  at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:100)
	  at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215)
	  at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	  at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	  at org.postgresql.Driver.makeConnection(Driver.java:466)
	  at org.postgresql.Driver.connect(Driver.java:265)
	  at java.sql.DriverManager.getConnection(DriverManager.java:664)
	  at java.sql.DriverManager.getConnection(DriverManager.java:208)
	  at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:78)
	  at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	  at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
	  at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	  at com.voodoodyne.postguice.dbcp.DBCPConnectionProvider.getConnection(DBCPConnectionProvider.java:66)
	  at com.orbitkit.houston.db.DBCPConnectionProvider.getConnection(DBCPConnectionProvider.java:21)
	  at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	  at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
	  at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
	  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	  at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.prepareQueryStatement(AbstractLoadPlanBasedLoader.java:198)
	  at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:162)
	  at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:104)
	  at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:285)
	  at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4521)
	  at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4511)
	  at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:571)
	  at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:539)
	  at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
	  at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:327)
	  at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108)
	  at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74)
	  at org.hibernate.internal.SessionImpl$$Lambda$411.521282693.applyEventToListener(Unknown Source:-1)
	  at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
	  at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1231)
	  at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1220)
	  at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:202)
	  at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2835)
	  at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2812)
	  at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl$$Lambda$410.1736971916.get(Unknown Source:-1)
	  at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2768)
	  at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2812)
	  at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3400)
	  at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3362)
	  at com.orbitkit.houston.entity.dao.DAO.load(DAO.java:119)
	  at com.orbitkit.houston.entity.dao.DAO.loadRequired(DAO.java:126)
	  at com.orbitkit.houston.entity.util.Loader.load(Loader.java:103)
	  at com.orbitkit.houston.entity.util.Loader.loadADMIN(Loader.java:91)
	  at com.orbitkit.houston.resource.VenuesResource.delete(VenuesResource.java:78)
	  at com.orbitkit.houston.resource.VenuesResource$$EnhancerByGuice$$173389595.GUICE$TRAMPOLINE(<generated>:-1)
	  at com.orbitkit.houston.resource.VenuesResource$$EnhancerByGuice$$173389595$$Lambda$408.207012443.apply(Unknown Source:-1)
	  at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74)
	  at com.orbitkit.houston.auth.AuthRequiredInterceptor.invoke(AuthRequiredInterceptor.java:42)
	  at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
	  at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:56)
	  at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
	  at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55)
	  at com.orbitkit.houston.resource.VenuesResource$$EnhancerByGuice$$173389595.delete(<generated>:-1)
	  at com.orbitkit.remote.errand.Noop.run(Noop.java:26)
	  at com.orbitkit.remote.errand.Noop$$EnhancerByGuice$$172033855.GUICE$TRAMPOLINE(<generated>:-1)
	  at com.orbitkit.remote.errand.Noop$$EnhancerByGuice$$172033855$$Lambda$407.356759862.apply(Unknown Source:-1)
	  at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74)
	  at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:64)
	  at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
	  at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55)
	  at com.orbitkit.remote.errand.Noop$$EnhancerByGuice$$172033855.run(<generated>:-1)
	  at com.orbitkit.remote.Errand.lambda$start$0(Errand.java:127)
	  at com.orbitkit.remote.Errand$$Lambda$405.1106634478.doFilter(Unknown Source:-1)
	  at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:94)
	  at com.orbitkit.remote.Errand.start(Errand.java:124)
	  at com.orbitkit.remote.errand.Noop.main(Noop.java:19)
```

**Comment by enocom** [comment]
That's quite interesting. Have you tried to create a minimal reproduction?

**Comment by depsypher** [comment]
Doh, looks like the query I was running just took a lot longer than I expected. Not sure why stepping through the debugger pointed to that area of code, but it's all working ok now. Sorry for the trouble.

**Comment by enocom** [comment]
No worries. Glad you figured it out.
