### ISSUE TITLE
Issue connecting to Google Cloud PostgreSQL from GAE project

### ISSUE THREAD

**Issue by ellenpoe** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#136]
Hey folks,

I'm trying to set up a Google App Engine project in standard mode with a Cloud SQL server (running postgres). I feel like I'm almost out of config hell, but I'm running into an issue that's got me a little stumped. I get an exception when I try to connect to the database. The stack trace might be able to explain it a little better than I can.

```org.eclipse.jetty.servlet.ServletHandler doHandle:  (ServletHandler.java:624)
org.eclipse.jetty.servlet.ServletHolder$1: java.lang.reflect.InvocationTargetException
	at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:597)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:661)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:183)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:123)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:692)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:655)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:625)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:817)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:269)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:349)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:299)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:275)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:127)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:247)
	at io.ktor.server.servlet.ServletApplicationEngine.init(ServletApplicationEngine.kt:75)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
	... 29 more
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:576)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at me.ellenhp.aprsbackend.DatabaseLayer.<init>(DatabaseLayer.kt:43)
	at me.ellenhp.aprsbackend.AprsBackendApplicationKt.main(AprsBackendApplication.kt:20)
	... 46 more
Caused by: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.postgresql.Driver.connect(Driver.java:295)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	... 50 more
Caused by: java.lang.IllegalArgumentException: address of type class java.net.InetSocketAddress are not supported. Use class jnr.unixsocket.UnixSocketAddress instead
	at jnr.unixsocket.UnixSocket.connect(UnixSocket.java:94)
	at org.postgresql.core.PGStream.<init>(PGStream.java:64)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:133)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:67)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:406)
	at org.postgresql.Driver.connect(Driver.java:274)
	... 55 more
```

I have my gross and ugly WIP commit pushed here: https://github.com/ellenpoe/APRSTools/tree/wip-backend/aprsbackend

This is confusing to me because it seems like the driver is choking on the socket that was created by this project, but this came directly from the sample code. Please let me know if you need any additional information.

Thanks!

**Comment by ellenpoe** [comment]
I forgot to mention, what makes this weird is that the socket factory thinks it's using unix sockets

2019-05-05 19:16:30.680 PDT
com.google.cloud.sql.core.CoreSocketFactory getInstance: First Cloud SQL connection, generating RSA key pair. (CoreSocketFactory.java:140)
2019-05-05 19:16:35.363 PDT
com.google.cloud.sql.core.CoreSocketFactory connect: Connecting to Cloud SQL instance [redacted] via unix socket. (CoreSocketFactory.java:189)
2019-05-05 19:16:37.259 PDT
[redacted].<stdout>: 02:16:37.259 [RequestFAF57B58] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to create/setup connection: Something unusual has occurred to cause the driver to fail. Please report this exception.

**Comment by ellenpoe** [comment]
The first suggestion from #134 fixed this problem. Nothing about this makes sense, but it's connecting now, and that's what counts I guess?
