### ISSUE TITLE
DataAccessResourceFailureException when using cloud-sql-connector-r2dbc-postgres

### ISSUE THREAD

**Issue by dm-cloud2023** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1621]
### The issue happens only when using GCP IAM connection

We are using spring boot 2.7.3
With below dependencies
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
</dependency>
<!-- For reactive DBC postgresql support: -->
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-postgresql</artifactId>
    <version>0.8.12.RELEASE</version>
    <scope>runtime</scope>
</dependency>
```
And for connecting to DB we are using below property :
`spring.r2dbc.url=r2dbc:postgresql://******:5432/****-db`

This set up is  working fine for all loads to application and we dont have any issues.

However we want to migrate to IAM connection, 
and we have added below dependency:
```
<dependency>
    <groupId>com.google.cloud.sql</groupId>
    <artifactId>cloud-sql-connector-r2dbc-postgres</artifactId>
    <version>1.11.1</version>
</dependency>
```
And the connection url is :
`spring.r2dbc.url=r2dbc:gcp:postgres://sa-user@project.iam:NONE@project:us-east1:instance-db/db-name?ENABLE_IAM_AUTH=true`

This setup also works fine for smaller loads to application but when the load to application increases we are seeing application server restarts with below exception in log:
`reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is reactor.pool.PoolShutdownException: Pool has been shut down
Caused by: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is reactor.pool.PoolShutdownException: Pool has been shut down
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[spring-r2dbc-5.3.22.jar:5.3.22]
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3730) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.22.jar:3.4.22]`

The above restart seems to be triggered from Kubernetes when health check from Kubernetes fails.
The Kubernetes does a periodic health check by /actuator/health and when this does not respond within time Kubernetes restarts the pod. We dont see this issue when we use `spring.r2dbc.url=r2dbc:postgresql://******:5432/****-db` to connect to DB.

* Although its a reactive project we are using spring @Async to do the DB read and save operation (find a record and update it)
* We are using default pool settings.
* We tried below change but it did not solve the issue :
1. update spring boot to 2.7.4
2. replace io.r2dbc to org.postgresql and use version 0.9.3.RELEASE : increasing this to 1.0 gave other exceptions.
3. updating cloud-sql-connector-r2dbc-postgres to 1.14.1

### Stacktrace

```bash
`reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is reactor.pool.PoolShutdownException: Pool has been shut down
Caused by: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is reactor.pool.PoolShutdownException: Pool has been shut down
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[spring-r2dbc-5.3.22.jar:5.3.22]
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3730) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.22.jar:3.4.22]`
```

### Steps to reproduce?

Add below dependency :
```
<dependency>
    <groupId>com.google.cloud.sql</groupId>
    <artifactId>cloud-sql-connector-r2dbc-postgres</artifactId>
    <version>1.11.1</version>
</dependency>
```
Make the connection url as :
`spring.r2dbc.url=r2dbc:gcp:postgres://sa-user@project.iam:NONE@project:us-east1:instance-db/db-name?ENABLE_IAM_AUTH=true`

Run the application with 200 request/sec  each request does read and write operation.

### Environment

All environments

**Comment by hessjcg** [comment]
Hi @dm-cloud2023,
Your database URL looks almost correct. Try this: 

`spring.r2dbc.url=r2dbc:gcp:postgres://sa-user%40project.iam:NONE@project:us-east1:instance-db/db-name?ENABLE_IAM_AUTH=true`

**Comment by dm-cloud2023** [comment]
Hi @hessjcg ,
My database URL has "%40" instead of @ , I have decoded it before pasting in question.
Also there is no issue with connection as the application works fine with smaller loads.

**Comment by enocom** [comment]
> when the load to application increases we are seeing application server restarts with below exception in log

What kind of load increase are we talking about?

Also is there any more of that stack trace? If the Java Connector is failing to connect, it will throw an exception and report the underlying issue.

**Comment by dm-cloud2023** [comment]
In our production env. when we were using IP based connection than we did not face this issue, however when we switched to IAM based connection we started getting this issue.
When we reverted back to IP based connection the issue was fixed .

Generally in lower environment we have smaller loads hence we do not see this issue when using IAM .
However in lower environment as we ramp up the load using some automation tool we can reproduce the issue.
Note : with IP based connection even in lower environment when we ramp up the load we dont see this issue.

Whenever this issue happens we observe that health check takes lot of time to respond and hence times out.
May be this is because even the health check waits in queue for connection and ultimately times out.

Below is the complete stack trace :
`reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is reactor.pool.PoolShutdownException: Pool has been shut down
Caused by: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is reactor.pool.PoolShutdownException: Pool has been shut down
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[spring-r2dbc-5.3.22.jar:5.3.22]
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3730) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.22.jar:3.4.22]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:96) ~[spring-cloud-sleuth-instrumentation-3.1.3.jar:3.1.3]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:95) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-pool-0.2.9.jar:0.2.9]
	at reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:292) ~[reactor-pool-0.2.9.jar:0.2.9]
	at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:430) ~[reactor-pool-0.2.9.jar:0.2.9]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:720) ~[reactor-pool-0.2.9.jar:0.2.9]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:117) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:101) ~[reactor-core-3.4.22.jar:3.4.22]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:96) ~[spring-cloud-sleuth-instrumentation-3.1.3.jar:3.1.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-pool-0.2.9.jar:0.2.9]
	at reactor.pool.SimpleDequePool.lambda$disposeLater$2(SimpleDequePool.java:195) ~[reactor-pool-0.2.9.jar:0.2.9]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8466) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
	at reactor.core.publisher.Mono.block(Mono.java:1706) ~[reactor-core-3.4.22.jar:3.4.22]
	at io.r2dbc.pool.ConnectionPool.dispose(ConnectionPool.java:264) ~[r2dbc-pool-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:319) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:149) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.7.3.jar:2.7.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-2.7.3.jar:2.7.3]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: reactor.pool.PoolShutdownException: Pool has been shut down
	... 41 common frames omitted`

**Comment by dm-cloud2023** [comment]
So we added logs to measure the time taken by the DB operations when we connect via IP address and via IAM.
We kept the load low so connection pool is always available.
We found out that when using IAM connection the DB operation time increases by 3-4 times compared to connection using IP address. We also logged the connection pool metrics to ensure there are no pending acquire connections.
So it seems since the time taken by DB operation is more when using IAM connection hence when the load increases the connection pool becomes full and is not emptied fast enough for next connection and thus application hangs and kube restarts the server.
Could you please let us know why we are facing latency when using IAM connection type, is it expected (Does IAM makes some verification call before each DB call ?) What are the ways we can resolve this ?

**Comment by ttosta-google** [comment]
Hello @dm-cloud2023. Sorry for the slow response.

There is an expected latency when performing database IAM authentication because internally it will talk to the remote GCP IAM service and it does take time.

Also Cloud SQL IAM database authentication has [restrictions](https://cloud.google.com/sql/docs/postgres/authentication#restrictions). There is quota applicable for the [IAM database authentication](https://cloud.google.com/sql/docs/quotas#cloud_sql_iam_database_authentication) which is `3000 per minute per instance`.

Does your load get close to this limit?

Alterative solutions:

1. Add a read replica and direct all their read traffic to the replica. This would mean two instances each with 3000 logins / minute.
2. Increase the pool size:

```
spring.r2dbc.pool.initial-size=
spring.r2dbc.pool.max-size=
```

3. Switch to database native authentication.

**Comment by ttosta-google** [comment]
Going to close this as stale. Feel free to re-open if we've missed something.
