### ISSUE TITLE
HikariPool CP resets to 0 when IAM authentication exception occurs

### ISSUE THREAD

**Issue by dawidstosur** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1729]
### Bug Description

I am encountering an issue with our Spring Boot service running on GCP Cloud Run, which connects to Cloud SQL (Postgres) using the `com.google.cloud.sql.postgres.SocketFactory` connector and `com.zaxxer:HikariCP` for connection pooling. The service utilizes IAM Authentication. We've observed that the connection pool, configured to maintain a minimum of 5 connections, intermittently drops to zero, leading to service downtime. This issue persists across all environments (dev, stage, prod) and appears unrelated to specific database instances or application logic.

The CP is configured to maintain a minimum of 5 connections refreshed every 10 mins. Right after the start CP is initialized as expected:

```
DEBUG 2023-12-06T20:22:18.766192802Z Connecting with URL: jdbc:postgresql://google/${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${CLOUD_SQL_INSTANCE}&enableIamAuth=true&sslmode=disable
...
DEBUG 2023-12-06T20:22:21.062219777Z PostgreSQL JDBC Driver 42.6.0
...
DEBUG 2023-12-06T20:22:21.188125251Z HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@4ba4f6a2
...
DEBUG 2023-12-06T20:22:21.188432656Z HikariPool-1 - After adding stats (total=5, active=0, idle=5, waiting=0)
```

CP is configured to refresh idle connections every 10 minutes and for a while most connections are refreshed without any problems but sometimes connection is not able to refresh due exception:

```
"Connection error: 
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1709)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:375)
	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:213)
	at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:77)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 15 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	... 25 common frames omitted
```

As result CP drops for a while below 5 or even down to 0, but this state is temporary,  probably after retry connection is initialised and CP is back to desired state of 5. Here is example:
```
DEBUG 2023-12-11T09:02:35.833876637Z HikariPool-1 - After cleanup stats (total=2, active=0, idle=2, waiting=0)
DEBUG 2023-12-11T09:02:35.834024813Z HikariPool-1 - Fill pool skipped, pool is at sufficient level.
DEBUG 2023-12-11T09:02:38.133855508Z Connecting with URL: jdbc:postgresql://google/${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${CLOUD_SQL_INSTANCE}&enableIamAuth=true&sslmode=disable
DEBUG 2023-12-11T09:02:53.333093897Z Connection error: org.postgresql.util.PSQLException: The connection attempt failed. at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl...
DEBUG 2023-12-11T09:02:58.162355621Z HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@cf44611
DEBUG 2023-12-11T09:02:58.162608076Z Connecting with URL: jdbc:postgresql://google/${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${CLOUD_SQL_INSTANCE}&enableIamAuth=true&sslmode=disable
DEBUG 2023-12-11T09:02:58.274055326Z HikariPool-1 - Add connection elided, waiting 1, queue 2
DEBUG 2023-12-11T09:02:58.276898499Z HikariPool-1 - Add connection elided, waiting 1, queue 2
DEBUG 2023-12-11T09:02:58.278249723Z HikariPool-1 - Add connection elided, waiting 1, queue 2
DEBUG 2023-12-11T09:02:58.279190248Z HikariPool-1 - Add connection elided, waiting 1, queue 2
DEBUG 2023-12-11T09:02:58.279869307Z HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@4f7623d8
DEBUG 2023-12-11T09:02:58.279927601Z HikariPool-1 - After adding stats (total=4, active=4, idle=0, waiting=0)
DEBUG 2023-12-11T09:02:58.280117233Z Connecting with URL: jdbc:postgresql://google/${DB_NAME}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${CLOUD_SQL_INSTANCE}&enableIamAuth=true&sslmode=disable
DEBUG 2023-12-11T09:02:58.405834391Z HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@7a00f602
DEBUG 2023-12-11T09:02:58.405923576Z HikariPool-1 - After adding stats (total=5, active=2, idle=3, waiting=0)
```

But situations gets worse when we get following error (usually after 1-2 hour after service start):

```
HikariPool-1 - Cannot acquire connection from data source
org.postgresql.util.PSQLException: FATAL: Cloud SQL IAM service account authentication failed for user "my-service@test-user-production.iam"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This exception seems not recoverable, and when it happens connection pool quickly drops to 0 and now new connection is added since then. Here is CP log that repeats every 30 seconds, with exactly same message which is already strange as it reports "pool is at sufficient level" and total=0.

```
DEBUG 2023-12-11T09:56:00.133822158Z HikariPool-1 - Before cleanup stats (total=0, active=0, idle=0, waiting=0)
DEBUG 2023-12-11T09:56:00.133950528Z HikariPool-1 - After cleanup stats (total=0, active=0, idle=0, waiting=0)
DEBUG 2023-12-11T09:56:00.134001437Z HikariPool-1 - Fill pool skipped, pool is at sufficient level.
...
DEBUG 2023-12-11T09:59:35.936835982Z HikariPool-1 - Before cleanup stats (total=0, active=0, idle=0, waiting=2)
DEBUG 2023-12-11T09:59:35.936958158Z HikariPool-1 - After cleanup stats (total=0, active=0, idle=0, waiting=2)
DEBUG 2023-12-11T09:59:35.937005310Z HikariPool-1 - Fill pool skipped, pool is at sufficient level.

```
In this state our service is essentially down as every user request that requires db access times out and we have no other choice than service restart.

We have been experiencing this issue across all our environments (development, staging, and production) for the past few weeks. All three environments are hosted on GCP and have similar resources, though the production environment has more powerful machines and a higher number of service instances. This suggests that the problem is not with the database instance, as it occurs in all three environments. Additionally, it is unlikely to be an issue with our application logic, as the error also arises when the service starts without processing any user requests, typically at night. The issue persists even when the only activity in the logs is HikariPool refreshes, and a restart seems to be the only solution.

In the production environment, our service is configured to always have a minimum of three instances running. When one instance becomes unresponsive, the other two generally remain operational, indicating that the issue is unlikely to be a connectivity problem between Cloud SQL and our Cloud Run service, as it would affect all instances simultaneously.

Do you have any idea what can I do to fix this problem ? It looks like its issue with connection pool or connector as connection pool gets to state its not able to recover from. In the same time other service instances  don't have this problem, or may have but at different time.

### Steps to reproduce?

This issue occurs sometimes few times per day but sometimes all day is ok. The problem its not deterministic so I can not tell what exactly has to be done to reproduce it. Sometimes connections pools is fine all the time (until GCP rotates instance) but sometimes we get into this situation relatively quickly about 90 mins after instance start.

As problem occurs  even when there is no user traffic it means that it should be reproducible with simplest cloud run service without business logic, only few dependencies needed and connection pool configuration.

### Environment

1. We are using newest dependencies version (we tried older but get same problem)
Dependencies:
```
com.zaxxer:HikariCP:5.0.1
com.google.cloud:spring-cloud-gcp-starter-sql-postgresql:4.8.2
	com.google.cloud.sql:postgres-socket-factory:1.14.0
	com.google.cloud:spring-cloud-gcp-starter:4.8.2 (*)
	org.postgresql:postgresql:42.6.0 (*)
	org.springframework.boot:spring-boot-starter-jdbc:3.1.4 (*)
```
2.
Configuration:
```
spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-name: ${DB_NAME}
                instance-connection-name: ${CLOUD_SQL_INSTANCE}
                enable-iam-auth: ${ENABLE_IAM_AUTH:true}
    datasource:
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 20
            max-lifetime: 540000
            minimum-idle: 5
            validation-timeout: 3000
            idle-timeout: 60000
```

We are connection to Postgres 15 instance on Cloud SQL.

**Comment by enocom** [comment]
Thanks for the issue. Are you running with "Always on CPU"?

**Comment by dawidstosur** [comment]
Regarding CPU allocation we are using default settings, here are our container general settings:
```
CPU allocation: CPU is only allocated during request processing
Startup CPU boost: Disabled
Concurrency: 250
Request timeout: 300 seconds
Execution environment: First generation (Default)
```

**Comment by enocom** [comment]
On the surface this looks like Cloud Run throttling the background refresh thread the Java Connector runs.

There are two things to try:

1. Enable "CPU Always Allocated" as described in [the docs](https://cloud.google.com/run/docs/configuring/cpu-allocation). If you have a steady flow of traffic, this is a reasonable price difference.
2. Otherwise, consider connecting through the Cloud SQL Proxy using the Unix socket. We document how to do that [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc.md#connection-via-unix-sockets). The downside in this approach is the Proxy run by Cloud Run doesn't support Auto IAM AuthN, but you can wire up your connection pool to dynamically retrieve the OAuth2 token as a password. There's an example [here](https://github.com/GoogleCloudPlatform/alloydb-java-connector/blob/main/alloydb-jdbc-connector/src/test/java/com/google/cloud/alloydb/AlloyDBDirectPathDataSource.java) for AlloyDB, but the approach would be the same for Cloud SQL.

**Comment by enocom** [comment]
Meanwhile, we're planning on supporting a lazy refresh as described here: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/992. That work is still probably a ways away though.
