### ISSUE TITLE
Invalid OAuth scope or ID token audience provided

### ISSUE THREAD

**Issue by pramod-prabhakar-kapase-db** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1904]
### Question

I am using socket factory with "cloudSqlGoogleCredentialsPath" with Tableau but it is giving below error, where as if I use same json with cloudsql auth proxy then I am able to connect. please let me know issue

CONNECTION STRING -

jdbc:postgresql:///DATABASE_NAME?cloudSqlInstance=PROJECT_ID:REGION:INSTANCE_NAME&socketFactory=com.google.cloud.sql.postgres.SocketFactory&password=NotNull&enableIamAuth=true&sslmode=disable&cloudSqlGoogleCredentialsPath=WINDOWS_PATH_FOR_SA_JSON 

ERROR - 

Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: 400 Bad Request
POST https://oauth2.googleapis.com/token
{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}, iss: tableau-gcp-dbg-sa@db-dev-x1hq-tableau-gcp-dbg.iam.gserviceaccount.com
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:129) ~[?:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:538) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:270) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:267) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:635) ~[?:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[jdbcserver.jar:20213.0.10]
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:582) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:233) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials.refreshIfExpired(OAuth2Credentials.java:204) ~[?:?]
	at com.google.cloud.sql.core.DefaultAccessTokenSupplier.lambda$get$0(DefaultAccessTokenSupplier.java:87) ~[?:?]
	at com.google.cloud.sql.core.RetryingCallable.call(RetryingCallable.java:67) ~[?:?]
	at com.google.cloud.sql.core.DefaultAccessTokenSupplier.get(DefaultAccessTokenSupplier.java:140) ~[?:?]

### Code

```Java
No code change made, just build and using postgres socket factory
```

**Comment by pramod-prabhakar-kapase-db** [comment]
API enable for SA -

privateca.googleapis.com
logging.googleapis.com
monitoring.googleapis.com
container.googleapis.com
stackdriver.googleapis.com
vpcaccess.googleapis.com
sqladmin.googleapis.com
storage-component.googleapis.com
storage.googleapis.com
bigquery.googleapis.com

**Comment by pramod-prabhakar-kapase-db** [comment]
Hi @ttosta-google 

Request you to please check and update me

**Comment by ttosta-google** [comment]
Hello @pramod-prabhakar-kapase-db

Thank you for bringing this issue to our attention. We have identified it as a bug on our end and will soon create a pull request (PR) to fix it.

I will keep you updated on the progress of this issue until it is fully resolved.

**Comment by ttosta-google** [comment]
@pramod-prabhakar-kapase-db 

We will merge the PR today but our next release is scheduled for April 16.

You should be able to build the version `1.17.1-SNAPSHOT` locally and use it in your application.

**Comment by ttosta-google** [comment]
@pramod-prabhakar-kapase-db The version `1.17.1` has been released.
