### ISSUE TITLE
support jdbc connection with unix domain socket in native image

### ISSUE THREAD

**Issue by czp3009** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1940]
### Feature Description

I'm sorry I don't really know where this issue should be submit, so I'll submit it here first, and let me know if it shouldn't be.

I've looked at the [previous archived repositories](https://github.com/GoogleCloudPlatform/native-image-support-java), but I don't know what repositories the previous functionality has been moved to.

I've submitted a PR to that repository before: https://github.com/GoogleCloudPlatform/native-image-support-java/pull/304

That PR add unix domain socket supporting in graalvm native images.

But now when I add dependency according to the new documentation, I still get the same error as before this PR

```
java.lang.ClassNotFoundException: jnr.ffi.provider.jffi.Provider
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:123) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:87) ~[na:na]
        at java.base@17.0.10/java.lang.Class.forName(DynamicHub.java:1322) ~[report-service:na]
        at java.base@17.0.10/java.lang.Class.forName(DynamicHub.java:1285) ~[report-service:na]
        at java.base@17.0.10/java.lang.Class.forName(DynamicHub.java:1278) ~[report-service:na]
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68) ~[na:na]
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57) ~[na:na]
        at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35) ~[report-service:na]
        at jnr.ffi.Runtime$SingletonHolder.<clinit>(Runtime.java:109) ~[na:na]
        at jnr.ffi.Runtime.getSystemRuntime(Runtime.java:70) ~[report-service:na]
        at jnr.unixsocket.SockAddrUnix.<init>(SockAddrUnix.java:46) ~[report-service:na]
        at jnr.unixsocket.SockAddrUnix$DefaultSockAddrUnix.<init>(SockAddrUnix.java:208) ~[na:na]
        at jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:174) ~[report-service:na]
        at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:47) ~[na:na]
        at com.google.cloud.sql.core.Connector.connect(Connector.java:106) ~[na:na]
        at com.google.cloud.sql.core.InternalConnectorRegistry.connect(InternalConnectorRegistry.java:179) ~[na:na]
        at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:63) ~[report-service:1.16.0]
        at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:45) ~[report-service:1.16.0]
```

I think that repository was using an older version of the code before moving it to another repository, so the code in the last batch of PRs didn't get moved to the new repository.

If this functionality should be moved to this repository, is it possible to merge the code from the previous PR to this repository?

**Comment by czp3009** [comment]
After reading the source code, I'm sure that https://github.com/GoogleCloudPlatform/native-image-support-java/blob/master/native-image-support/src/main/java/com/google/cloud/nativeimage/features/gcp/CloudSqlFeature.java in the old repository has been moved to https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/src/main/java/com/google/cloud/sql/nativeimage/CloudSqlFeature.java in this repository.

But not include [last PR](https://github.com/GoogleCloudPlatform/native-image-support-java/pull/304) in old repository. Which results in lost the support for unix domain sockets in the graalvm native image.

If you guys manage both repositories, please merge the last PR into this one.

By the way, I see that there's another issue: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/217

The 'connecting directly' in that issue is means unix domain socket in graalvm native image. The last PR already solved this problem in the old repository, if merge back into this repository also can solve that issue.

**Comment by hessjcg** [comment]
@czp3009 Thanks for the heads up. I'll port https://github.com/GoogleCloudPlatform/native-image-support-java/pull/304 over to this repo.

**Comment by hessjcg** [comment]
A quick status update: it seems like we can't port this over exactly 1:1. Perhaps there are different versions of graalvm  installed. I'm looking into it. I would welcome help from someone more experienced with graalvm.

**Comment by hessjcg** [comment]
PR #1947 is a dead end. It won't work because we need to be able to compile the source code using JDK 8, but the configuration required to add the proxy. I'm going to try again replacing core/src/main/java/com/google/cloud/sql/nativeimage/CloudSqlFeature.java with a JSON file containing the Graalvm reflection configuration.

**Comment by czp3009** [comment]
hi @hessjcg , i think it's a good idea to register the proxy with a JSON file, instead of replacing the entire CloudSqlFeature with JSON.

for example(proxy-config.json):
```json
[
  {
    "interfaces": [
      "jnr.unixsocket.Native$LibC",
      "jnr.ffi.provider.LoadedLibrary"
    ]
  },
  {
    "interfaces": [
      "jnr.enxio.channels.Native$LibC",
      "jnr.ffi.provider.LoadedLibrary"
    ]
  }
]
```

**Comment by hessjcg** [comment]
Ok, we are getting closer. The classes now load, but it seems like the resources JNI library resources are not being loaded correctly. When I run the test, I get this error: (See #1961) 

```
java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/x86_64-Linux/libjffi-1.2.so, /jni/x86_64-Linux/libjffi-1.2.so]
```

I think that the nativeimage resource configuration is not correct yet.
