### ISSUE TITLE
Certificate error for psc CloudSQL Postgres Instance 

### ISSUE THREAD

**Issue by pramod-prabhakar-kapase-db** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#2074]
### Question

Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: [CONNECTION_STRING] The Google Cloud SQL Admin API failed for the project "INSTANCE". Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### Additional Details

Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: [CONNECTION_STRING] The Google Cloud SQL Admin API failed for the project "INSTANCE". Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:525) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:102) ~[jdbcserver.jar:20213.0.10]
	at com.google.cloud.sql.core.RefreshAheadStrategy.handleRefreshResult(RefreshAheadStrategy.java:238) ~[?:?]
	at com.google.cloud.sql.core.RefreshAheadStrategy.lambda$startRefreshAttempt$1(RefreshAheadStrategy.java:230) ~[?:?]
	at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:157) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:144) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[jdbcserver.jar:20213.0.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	... 3 more
Caused by: java.lang.RuntimeException: [CONNECTION_STRING] The Google Cloud SQL Admin API failed for the project "INSTANCE". Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.addExceptionContext(DefaultConnectionInfoRepository.java:491) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.fetchMetadata(DefaultConnectionInfoRepository.java:326) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$getConnectionInfo$0(DefaultConnectionInfoRepository.java:143) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[jdbcserver.jar:20213.0.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	... 3 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:151) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[?:?]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:565) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:506) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:616) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$fetchMetadata$9(DefaultConnectionInfoRepository.java:252) ~[?:?]
	at com.google.cloud.sql.core.RetryingCallable.call(RetryingCallable.java:69) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.fetchMetadata(DefaultConnectionInfoRepository.java:253) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$getConnectionInfo$0(DefaultConnectionInfoRepository.java:143) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[jdbcserver.jar:20213.0.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[?:?]
	at sun.security.validator.Validator.validate(Unknown Source) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:151) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[?:?]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:565) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:506) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:616) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$fetchMetadata$9(DefaultConnectionInfoRepository.java:252) ~[?:?]
	at com.google.cloud.sql.core.RetryingCallable.call(RetryingCallable.java:69) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.fetchMetadata(DefaultConnectionInfoRepository.java:253) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$getConnectionInfo$0(DefaultConnectionInfoRepository.java:143) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[jdbcserver.jar:20213.0.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	... 3 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source) ~[?:?]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[?:?]
	at java.security.cert.CertPathBuilder.build(Unknown Source) ~[?:?]
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[?:?]
	at sun.security.validator.Validator.validate(Unknown Source) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:151) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[?:?]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:565) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:506) ~[?:?]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:616) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$fetchMetadata$9(DefaultConnectionInfoRepository.java:252) ~[?:?]
	at com.google.cloud.sql.core.RetryingCallable.call(RetryingCallable.java:69) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.fetchMetadata(DefaultConnectionInfoRepository.java:253) ~[?:?]
	at com.google.cloud.sql.core.DefaultConnectionInfoRepository.lambda$getConnectionInfo$0(DefaultConnectionInfoRepository.java:143) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[jdbcserver.jar:20213.0.10]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[jdbcserver.jar:20213.0.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	... 3 more
2024-09-19 11:23:05.874 +0530 (,,,,2,1) grpc-default-executor-1 : INFO  com.tableau.connect.grpc.GrpcProtocolService - End local request 1 /constructProtocol.

**Comment by pramod-prabhakar-kapase-db** [comment]
any update on this?

**Comment by pramod-prabhakar-kapase-db** [comment]
Hi Team, Can you please help

**Comment by pramod-prabhakar-kapase-db** [comment]
no action needed, corrected configuration

**Comment by enocom** [comment]
@pramod-prabhakar-kapase-db would you mind elaborating on what problem you had and how you fixed it? I wonder if this could be documented for others.
