### ISSUE TITLE
Failed to update metadata for Cloud SQL instance (java.net.SocketException: Broken pipe )

### ISSUE THREAD

**Issue by tkgreg** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#267]
## Question
I have a Cloud Function which uses Micronaut framework when I deploy it to the Cloud I see in logs next messages

```
java.lang.RuntimeException: [*******] Failed to update metadata for Cloud SQL instance.
	at com.google.cloud.sql.core.CloudSqlInstance.addExceptionContext(CloudSqlInstance.java:455)
	at com.google.cloud.sql.core.CloudSqlInstance.fetchMetadata(CloudSqlInstance.java:322)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLException: readHandshakeRecord
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1320)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:148)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)
	at com.google.cloud.sql.core.CloudSqlInstance.fetchMetadata(CloudSqlInstance.java:277)
	... 9 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
		... 20 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeChangeCipherSpec(SSLSocketOutputRecord.java:221)
	at java.base/sun.security.ssl.OutputRecord.changeWriteCiphers(OutputRecord.java:162)
	at java.base/sun.security.ssl.ChangeCipherSpec$T10ChangeCipherSpecProducer.produce(ChangeCipherSpec.java:118)
	at java.base/sun.security.ssl.Finished$T12FinishedProducer.onProduceFinished(Finished.java:395)
	at java.base/sun.security.ssl.Finished$T12FinishedProducer.produce(Finished.java:379)
	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
	at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1403)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
	... 21 more
```

It appears in an hour after successful deployment. It works fine but looks like cloud function has a background process which is not expected behaviour.

What can I tune to stop this background process?

## Additional Context

Java Version: 11
Micronaut version: 2.0.1
Version: com.google.cloud.sql:postgres-socket-factory:1.0.16

My datasource connection config

```
datasources:
  default:
    url: jdbc:postgresql:///lead-server?cloudSqlInstance=not_real_cloud_instance_name&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    driverClassName: org.postgresql.Driver
    username: username
    password: '******'
    maximum-pool-size: 1
    minimum-idle: 0
    max-idle: 1
    idle-timeout: 10000
```

**Comment by shubha-rajan** [comment]
Hi @tkgreg, thanks for your question. So that background process that you are describing is the process to refresh SSL certs and maintain your secure connection. You can't disable it, and probably don't want to. The errors in your logs are failed refresh attempts, and it's hard to say what exactly is causing them. Cloud Functions scales down CPU when the function is inactive, which could be a possible cause. Regardless of why the refresh attempt is failing, it will be automatically retried, and since your function is working, we can assume it's eventually successful.

**Comment by tkgreg** [comment]
Thank you for the quick response. Now it's clear.

**Comment by maguro** [comment]
> Hi @tkgreg, thanks for your question. So that background process that you are describing is the process to refresh SSL certs and maintain your secure connection. You can't disable it, and probably don't want to. The errors in your logs are failed refresh attempts, and it's hard to say what exactly is causing them. Cloud Functions scales down CPU when the function is inactive, which could be a possible cause. Regardless of why the refresh attempt is failing, it will be automatically retried, and since your function is working, we can assume it's eventually successful.

Wouldn't it make sense to not log the error if it's expected to be handled at a higher level?  That higher level retry code would have the responsibility of logging an error if it could not recover after retrying, etc.?

**Comment by enocom** [comment]
Without having spent much time in this code, I think we do such retries in place now and try to surface errors if a retry fails. But either way (as I mentioned on the other issue), I'd hope that https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/561 makes these background refresh problems largely go away. If you're seeing problems on the latest version, let's open an issue and we can deal with it one way or another.

**Comment by tianbiao** [comment]
Hi @enocom What's the maximum number and interval of such retries? The error logs will be logged for each failure, our team is using google monitor to raise alert for error level logs. we want to come up with a policy of ignoring such error logs from monitor.

**Comment by enocom** [comment]
@tianbiao would you mind opening a new question for this? We can maybe even document this better for future users as well.
