### ISSUE TITLE
SSLHandshakeException: bad_certificate when connecting with r2dbc-postgres

### ISSUE THREAD

**Issue by pcthomatos** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#288]
## Question
Hello, I'm using R2DBC with postgres in GCP and while the connection works, it seems like the cert has issues after some time. And I start to get errors like this:
```
org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is 
io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to 35.245.149.98:3307 at 
org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:70) at 
reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3284) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:88) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214) at 
reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:396) at 
reactor.pool.SimplePool.lambda$drainLoop$7(SimplePool.java:206) at 
reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:152) at 
reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:147) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at 
reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at 
reactor.core.publisher.Mono.subscribe(Mono.java:4218) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at 
reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at 
reactor.core.publisher.Mono.subscribe(Mono.java:4218) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) at 
reactor.core.publisher.Operators.error(Operators.java:196) at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) at 
reactor.core.publisher.Mono.subscribe(Mono.java:4218) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.onError(MonoDelayUntil.java:175) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134) at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185) at 
reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1802) at 
reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onError(MonoIgnoreThen.java:235) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onError(MonoSubscribeOn.java:150) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97) at 
reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:83) at 
java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) at 
java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) at 
java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) at 
java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) at 
io.r2dbc.postgresql.client.AbstractPostgresSSLHandlerAdapter.completeHandshakeExceptionally(AbstractPostgresSSLHandlerAdapter.java:73) at 
io.r2dbc.postgresql.client.AbstractPostgresSSLHandlerAdapter.operationComplete(AbstractPostgresSSLHandlerAdapter.java:55) at 
io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) at 
io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) at 
io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) at 
io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) at 
io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) at 
io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) at 
io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) at 
io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1291) at 
io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1273) at 
io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) at 
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) at 
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) at 
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at 
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at 
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at 
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at 
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at 
io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) at 
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) at 
io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) at 
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at 
io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at 
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at 
java.base/java.lang.Thread.run(Thread.java:834) Caused by: 
io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to 35.245.149.98:3307 at 
io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:222) at 
reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3284) at 
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ... 64 common frames omitted 
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate at 
java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131) at 
java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117) at 
java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313) at 
java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) at 
java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186) at 
java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) at 
java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681) at 
java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636) at 
java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454) at 
java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433) at 
java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637) at 
io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282) at 
io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372) at 
io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ... 18 common frames omitted
```

Does SSL need to be turned off? Or am I misconfiguring something?
my connection string looks like this:
`r2dbc:gcp:postgres://connectionString/dbName`

**Comment by shubha-rajan** [comment]
Hi @pcthomatos, thanks for the question. About how long was the application running before you started seeing these error messages?

**Comment by pcthomatos** [comment]
It was just under 24 hours it seems - keep in mind this is over the weekend so we're not getting much traffic.

2020-09-19 14:15 - Deployed

2020-09-20 12:36 - Errors appear

**Comment by shubha-rajan** [comment]
Where is your application deployed? There might be an issue with the background task to refresh the certs, but we can't know for sure until we reproduce the error.

**Comment by pcthomatos** [comment]
it's in us-east1

**Comment by shubha-rajan** [comment]
I meant, is it deployed to App Engine, Cloud Run etc. ? Sorry for the lack of clarity

**Comment by pcthomatos** [comment]
haha Kubernetes sorry.

**Comment by pcthomatos** [comment]
And we're using spring-boot-starter-data-r2dbc

**Comment by shubha-rajan** [comment]
Some additional questions:
What version of Java are you using?
What version of the Cloud SQL connector and the r2dbc-posgresql connector are you using? 
Did the application stop working after you saw the errors?

**Comment by pcthomatos** [comment]
- What version of Java are you using?
  - 11
- What version of the Cloud SQL connector and the r2dbc-postgresql connector are you using?
  - I was using:
     - spring-boot-starter-parent:2.3.0.RELEASE
     - org.springframework.boot.spring-boot-starter-data-r2dbc:2.3.0-Release
     - com.google.cloud.sql.postgres-socket-factory:1.1.0
     - com.google.cloud.sql.cloud-sql-connector-r2dbc-postgres:1.1.0
     - io.r2dbc.r2dbc-postgresql:0.8.5.RELEASE



- Did the application stop working after you saw the errors?
  - No the application functioned but couldn't connect to the database, so it was throwing 500 errors for certain requests.

**Comment by pcthomatos** [comment]
This problem seems to have gone away when I upgraded from Spring Boot 2.3.0 to 2.3.4

**Comment by shubha-rajan** [comment]
Good to know! We weren't able to replicate this on our end (but we weren't using spring boot). I guess a good practice would be to use the latest stable version of all of your dependencies.

**Comment by BobDeBrabander** [comment]
I had this issue as well, but it turns out that for us the issue was that we didn't specify the following property:
`spring.cloud.gcp.project-id`

We didn't specify it because the spring-boot-starter-data-r2dbc doesn't have support yet for auto-injecting a cloud sql connection factory. Hence we had to specify the connection-url manually and we bypassed specifying that property.
We made another issue for this specific support: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/205 

We had ssl-certificate time-outs about every hour and after specifying the property, it has been fine for the past 4 hours.

**Comment by BobDeBrabander** [comment]
> I had this issue as well, but it turns out that for us the issue was that we didn't specify the following property:
> `spring.cloud.gcp.project-id`
> 
> We didn't specify it because the spring-boot-starter-data-r2dbc doesn't have support yet for auto-injecting a cloud sql connection factory. Hence we had to specify the connection-url manually and we bypassed specifying that property.
> We made another issue for this specific support: [GoogleCloudPlatform/spring-cloud-gcp#205](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/205)
> 
> We had ssl-certificate time-outs about every hour and after specifying the property, it has been fine for the past 4 hours.

Seems like I was wrong, we still see cases in our logs. I suppose there was something wrong with the logging platform on our side.

**Comment by BobDeBrabander** [comment]
Found out what it was. Specifying the bean manually for the connectionFactory seems to gives issues. The correct way to do it if you have the `spring-boot-starter-data-r2dbc` is to specify the `spring.r2dbc.url` property. You can either include the password in this url (as specified in the documentation) or leave it out and specify in the `spring.r2dbc.password` property

**Comment by porfirioribeiro** [comment]
I'm having the same problem, but when the service is running on GKE it has no issues, it's just locally or on a dev-server using a service account that it gives us this problem.

**Comment by kurtisvg** [comment]
Hey folks -- if you are experiencing this issue, the best thing to do is open up a new issue with additional information (and ideally include an example to reproduce). It's incredibly hard for us to troubleshooting and debug an issue if we aren't able to reproduce it ourselves.
