### ISSUE TITLE
Connecting with credentials lacking privileges produces vague error message

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#44]
When I provide credentials that lack the required privileges for Cloud SQL, I'm getting a very vague message on an endless loop:

`Re-throwing cached exception due to attempt to refresh instance information too soon after error.`

It would be great if we could actually log the reason why the running operation is failing.

**Comment by laixer** [comment]
Please provide the exception message. As the message indicates, this causes the original exception to be rethrown to the client. 

It sounds like your client code (or Spring code) is potentially swallowing the exception and retrying without relaying the original message to the user.

**Comment by joaoandremartins** [comment]
No exception is being swallowed on user code. It seems like if anything, it's either not being thrown in the first place or is being swollen by this library.

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java#L213

Also, I just found out that, for some reason, I was only able to get credentials to work with the Project/Editor role. Using only Cloud SQL/Editor is insufficient, not sure if that is expected (I didn't expect it).

In any case, switching over to the correct roles in IAM resolves the issue.

**Comment by laixer** [comment]
It's rethrown right below the line you linked: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/0f6ff69daa823d2123a2b357cb75268b24cf5a3f/core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java#L215

Connectivity requires the Cloud SQL Client role.

**Comment by laixer** [comment]
You can try one of the sample applications in the repo and you will see that it displays the full error message and does not retry.

**Comment by joaoandremartins** [comment]
Ah, apologies, it turns out it was HikariCP swallowing the exception.

Then I think all is good on this side. The only suggestion I would make is that the role doesn't need to be as broad as Editor/Owner, I think simply Cloud SQL Client could do it.

---
```
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2282)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2035)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to obtain ephemeral certificate for Cloud SQL Instance [xxx]. Make sure [xxx] has Editor or Owner role on the project.
	at com.google.cloud.sql.core.SslSocketFactory.obtainEphemeralCertificate(SslSocketFactory.java:470)
	at com.google.cloud.sql.core.SslSocketFactory.fetchInstanceSslInfo(SslSocketFactory.java:303)
	at com.google.cloud.sql.core.SslSocketFactory.getInstanceSslInfo(SslSocketFactory.java:264)
	at com.google.cloud.sql.core.SslSocketFactory.createAndConfigureSocket(SslSocketFactory.java:183)
	at com.google.cloud.sql.core.SslSocketFactory.create(SslSocketFactory.java:152)
	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:48)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2203)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2236)
	... 22 more
```

**Comment by laixer** [comment]
Yes, you're right. The message has not been updated since we introduced curated IAM roles.
