### ISSUE TITLE
JdbcPostgresIamAuthIntegrationTests fails with SSLHandshakeException

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#515]
I'm trying to get IAM to work and experimenting with the `JdbcPostgresIamAuthIntegrationTests`, but it's not working for me.

I'm getting this error:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.513 s <<< FAILURE! - in com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests
[ERROR] com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.pooledConnectionTest  Time elapsed: 2.456 s  <<< ERROR!
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)
Caused by: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)
```

Googling around, I found a suggestion to set `-Djdk.tls.client.protocols=TLSv1.2`, but that doesn't work either.

```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.522 s <<< FAILURE! - in com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests
[ERROR] com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.pooledConnectionTest  Time elapsed: 2.449 s  <<< ERROR!
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The connection attempt failed.
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)
Caused by: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)

[ERROR] com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.pooledConnectionTest  Time elapsed: 2.45 s  <<< ERROR!
java.lang.NullPointerException
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.dropTableIfPresent(JdbcPostgresIamAuthIntegrationTests.java:106)
```

My environment: MacOS, openjdk 11.0.2.

**Comment by shubha-rajan** [comment]
Thanks for catching this @meltsufin. I was able to replicate this by switching to an older Java version (11.0.3) What Java version are you using? There's a [bug](https://bugs.openjdk.java.net/browse/JDK-8236039) in the TLS 1.3 implementation of early Java 11 versions. Try upgrading to Java 11.0.11 or 8.0.292 (the latest in each release track).

**Comment by meltsufin** [comment]
Thanks for the suggestion to upgrade the JDK. I upgraded to 11.0.11 and that particular error went away. However, I'm now getting `passward authentication failed`, and I don't know how to debug that further.

```
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.665 s <<< FAILURE! - in com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests
[ERROR] com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.pooledConnectionTest  Time elapsed: 2.607 s  <<< ERROR!
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: FATAL: password authentication failed for user "meltsufin@google.com"
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "meltsufin@google.com"
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.setUpPool(JdbcPostgresIamAuthIntegrationTests.java:88)

[ERROR] com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.pooledConnectionTest  Time elapsed: 2.608 s  <<< ERROR!
java.lang.NullPointerException
        at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.dropTableIfPresent(JdbcPostgresIamAuthIntegrationTests.java:106)

```

**Comment by meltsufin** [comment]
Ok, I got past my last issue by adding the user to the list of users on the instance.
