### ISSUE TITLE
28463416 case on GCP SUPPORT: about Cloud-Run SQL-Auth-Proxy Cloud-SQL mysql error: doesn't refresh ephemeral certificate

### ISSUE THREAD

**Issue by vincenzo-mazzotta** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#547]
## Bug Description

Joan Grau Google Support Team has opened an internal GCP Support request on Case 28463416 on GCP Support about this issue. Please see https://console.cloud.google.com/support/cases/detail/28463416?project=lmit-link-utili-itlm for more details, logs with ssl log verbose enabled.
Joan Grau asked us to open here the same issue and add him to follow it.
We need to close this issue ASAP to allow us to deploy production solution of application we have tried to solve it without success as Joan Grau so we hope you can help to solve it.

In concrete **only on GCP infrastructure** a Cloud Run with a Java8 Spring Boot application (An API REST app for backend) with SQL Auth Proxy enable on a Cloud SQL mysql when start springboot all works fine, HikariCP got 10 connection after around 1h try to refresh connection pool and it can't get connection with error:

**Caused by: java.lang.RuntimeException: [lmit-link-utili-itlm:europe-west1:test] Failed to create ephemeral certificate for the Cloud SQL instance.**

This problem doesn't appear on GKE infrastructure only on Cloud Run as library or instance of SQL Auth Proxy can't refresh ephemeral certificate.

**The strange thing is that in my local machine using downloaded and launched SQL Auth Proxy all works fine refreshing ephemeral certificate every 1h - 1h and 15m, but on GCP infrastructure after 1h-1h and 15m from startup of Spring Boot app on Cloud Run can't refresh connections and nothing works of application.**

## Example code (or command)
```java application-test.properties
// example
- HikariCP Connection pool configuration:
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.pool-name=LinkUtili-Hikari-Connection-Pool
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.max-lifetime=600
spring.datasource.hikari.keepaliveTime=600
spring.datasource.username=root
spring.datasource.password=****************
spring.datasource.url=jdbc:mysql:///LinkUtili?cloudSqlInstance=lmit-link-utili-itlm:europe-west1:test&socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.datasource.ipTypes=PUBLIC
```
```java 
//Application use Hibernate and JPA:
...
```

```pom.xml
   <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
<!-- Used for sql auth proxy unix socket STARTED-->
        <dependency>
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>mysql-socket-factory</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.32.1</version>
        </dependency>
<!-- Used for sql auth proxy unix socket ENDED-->
<!-- Connector mysql STARTED -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>4.0.3</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
<!-- Connector mysql ENDED -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.200</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </dependency>

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.9.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.12.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.5.9</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.18</version>
        </dependency>

        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.1.2</version>
        </dependency>
    </dependencies>

```
## Stacktrace
```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1006) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.23.jar!/:8.0.23]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) [HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) [HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) [HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) [HikariCP-4.0.3.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
**Caused by: java.lang.RuntimeException: [lmit-link-utili-itlm:europe-west1:test] Failed to create ephemeral certificate for the Cloud SQL instance.**
	at com.google.cloud.sql.core.CloudSqlInstance.addExceptionContext(CloudSqlInstance.java:574) ~[jdbc-socket-factory-core-1.3.0.jar!/:na]
	at com.google.cloud.sql.core.CloudSqlInstance.fetchEphemeralCertificate(CloudSqlInstance.java:515) ~[jdbc-socket-factory-core-1.3.0.jar!/:na]
	at com.google.cloud.sql.core.CloudSqlInstance.lambda$performRefresh$0(CloudSqlInstance.java:330) ~[jdbc-socket-factory-core-1.3.0.jar!/:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[guava-30.1.1-android.jar!/:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) ~[guava-30.1.1-android.jar!/:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[guava-30.1.1-android.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_212]
	... 3 common frames omitted
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_212]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_212]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_212]
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[na:1.8.0_212]
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:879) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:850) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:720) ~[na:1.8.0_212]
	at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1144) ~[na:1.8.0_212]
	at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1280) ~[na:1.8.0_212]
	at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1190) ~[na:1.8.0_212]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:369) ~[na:1.8.0_212]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[na:1.8.0_212]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_212]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_212]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[na:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[na:1.8.0_212]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) ~[na:1.8.0_212]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113) ~[google-http-client-1.39.2.jar!/:1.39.2]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[google-http-client-1.39.2.jar!/:1.39.2]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[google-http-client-1.39.2.jar!/:1.39.2]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514) ~[google-api-client-1.32.1.jar!/:1.32.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455) ~[google-api-client-1.32.1.jar!/:1.32.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565) ~[google-api-client-1.32.1.jar!/:1.32.1]
	at com.google.cloud.sql.core.CloudSqlInstance.fetchEphemeralCertificate(CloudSqlInstance.java:513) ~[jdbc-socket-factory-core-1.3.0.jar!/:na]
	... 11 common frames omitted
```

## How to reproduce

  1. Create a simple Spring Boot application with same dependencies/versions and resources for HikariCP above on your Cloud DB and credentials.
  2. Create an API REST controller/service/repository to do a query on a table on your cloud DB
  3. deploy on GCP on a Cloud Run as spring boot and see the error after 1h-1h and 15m that startup the Springboot.

## Environment

1. OS type and version: Unix by docker image on Alpine Linux Project openjdk:8-jre-alpine
2. Java SDK version: `8`
2. Socket Factory version: 1.3.0

## Log Explorer (10000 rows):
[downloaded-logs-20210713-171916.zip](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/files/6815047/downloaded-logs-20210713-171916.zip)

**Comment by shubha-rajan** [comment]
Hi @vincenzo-mazzotta  Please take a look at https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/267. The errors are likely failed refresh attempts due to Cloud Run's autoscaling when the application is inactive. First, please update your application to use the `v1.3.1` of `mysql-socket-factory`, to rule out any bugs in upstream dependencies that have since been resolved, then redeploy and run your application. As long as your app recovers from the errors when it hits them, the occasional "broken pipe" error on Cloud Run is to be expected.

**Comment by vincenzo-mazzotta** [comment]
shubha-rajan  as wrote to Joan Grau of GCP support, **we have solved the issue changing dependency respect message on CASE on GCP Support of July 13, 2021 at 1:25:56 PM GMT+2 and using unix socket.**

**Google documentation and here in github doesn't help:**


        <dependency>
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>mysql-socket-factory-connector-j-8</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.32.1</version>
        </dependency>


        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>4.0.3</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.25</version>
        </dependency>


Changed in application.properties to use unix socket (it isn't clear in documentation example is only for TCP connection to DB):
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.pool-name=LinkUtili-Hikari-Connection-Pool
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.max-lifetime=600
spring.datasource.hikari.keepaliveTime=600
spring.datasource.url=jdbc:mysql:///LinkUtili?unixSocketPath=/cloudsql/lmit-link-utili-itlm:europe-west1:test
spring.datasource.username=***********
spring.datasource.password=***********
spring.datasource.socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.datasource.cloudSqlInstance=lmit-link-utili-itlm:europe-west1:test
spring.datasource.ipTypes=PUBLIC

where the fondamental substring needed in spring.datasource.url parameter is:
unixSocketPath=/cloudsql/lmit-link-utili-itlm:europe-west1:test

**Comment by enocom** [comment]
@vincenzo-mazzotta Will you help clarify what you mean here?

> Please remove previous version mysql-socket-factory-connector-j-8 that don't work.

> Google documentation and here in github doesn't help:

It sounds like you're suggesting the documentation (and maybe something in the README) could help future users who encounter the same problem. Is that correct?

**Comment by vincenzo-mazzotta** [comment]
Hi @enocom,
 the socket factory 1.3.0 in first messages doesn't work we have substitute  with
        <groupId>com.google.cloud.sql</groupId>
        <artifactId>mysql-socket-factory-connector-j-8</artifactId>
        <version>1.3.1</version>
Added unixsocket parameter in dsn as wrote in previous comment above and all works fine.

The bug is in library:
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>mysql-socket-factory</artifactId>
            <version>1.3.0</version>

**Comment by vincenzo-mazzotta** [comment]
SOLVED!
Lost 3 days to fix it :(

**Comment by vincenzo-mazzotta** [comment]
**BE CAREFULL with this attribute in DSN for unix socket:**
spring.datasource.url=jdbc:mysql:///LinkUtili?**unixSocketPath=/cloudsql/lmit-link-utili-itlm:europe-west1:test**
For us lmit-link-utili-itlm:europe-west1:test is the connection name that you can find in you istance of Cloud SQL.
This substring is fix don't modify **unixSocketPath=/cloudsql/**

**Comment by enocom** [comment]
Sorry to hear that you lost 3 days to fix the problem. I'm glad you got it working in the end, though.

**Comment by enocom** [comment]
@shubha-rajan Shall we add an example here so that others don't get tripped up by this?

https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc-mysql.md#connection-via-unix-sockets

**Comment by vincenzo-mazzotta** [comment]
Please add this example on GCP documentation. It's fundamental that
documentation on GCP is updated.

Kind regards

Il Ven 16 Lug 2021, 16:14 Eno Compton ***@***.***> ha scritto:
