### ISSUE TITLE
PostgreSQL connection fails due to java.net.UnknownHostException: google

### ISSUE THREAD

**Issue by kansuke231** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#55]
Hi all.
I am using postgres-socket-factory for connecting to Cloud SQL from a local java Spark application. I have constructed a jdbc url using an app in examples/getting-started and seemed fine. However, the line `connection = DriverManager.getConnection(jdbcUrl, username, password);` yields an error `java.net.UnknownHostException: google`. I searched on the Internet and found this log saying that the custom socketFactory is not being used at all: https://groups.google.com/forum/#!msg/google-cloud-sql-discuss/SAKNzasU5d4/vDSagB7uAQAJ but I have no clue why it's not begin used.
Any help would be highly appreciated. Thank you!

**Comment by laixer** [comment]
Unfortunately, there's not enough information here to be able to provide any advice.
Can you share the URL you are using? (Feel free to mask out the instance name)

If you could share a small repro that I can run myself that would be even better.

**Comment by kansuke231** [comment]
@laixer Thanks for the quick reply. 

Since I'm working on a private repo, I cannot let you run.

Here is the jdbc url string with some masking: `"jdbc:postgresql://google/postgres?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=foo-bar-111111:us-central1:some-instance-name"`.

I have this in pom.xml:
```
 <dependency>
          <groupId>com.google.cloud.sql</groupId>
          <artifactId>postgres-socket-factory</artifactId>
          <version>1.0.4</version>
      </dependency>
```

And here is the stacktrace:
```
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:152)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.lingk.transformer.provider.impl.GoogleCloudSqlSink.insert(GoogleCloudSqlSink.java:65)
	at io.lingk.transformer.SparkTopologyCreator.handleInsertStatement(SparkTopologyCreator.java:373)
	at io.lingk.transformer.SparkTopologyCreator.main(SparkTopologyCreator.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.net.UnknownHostException: google
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 19 more
```

**Comment by laixer** [comment]
Can you create a standalone repro not relating to the project you are working on?
Something is throwing away the socketFactory argument and I can't easily tell what it is.

**Comment by kansuke231** [comment]
Ok, so I added the following dependency in pom.xml
```
 <dependency>
          <groupId>org.postgresql</groupId>
          <artifactId>postgresql</artifactId>
          <version>42.1.1</version>
      </dependency>
```
and I am seeing a different error:
```
org.postgresql.util.PSQLException: The SocketFactory class provided com.google.cloud.sql.postgres.SocketFactory could not be instantiated.
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:41)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.lingk.transformer.provider.impl.GoogleCloudSqlSink.insert(GoogleCloudSqlSink.java:65)
	at io.lingk.transformer.SparkTopologyCreator.handleInsertStatement(SparkTopologyCreator.java:373)
	at io.lingk.transformer.SparkTopologyCreator.main(SparkTopologyCreator.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.sql.postgres.SocketFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:43)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:37)
	... 16 more
org.postgresql.util.PSQLException: The SocketFactory class provided com.google.cloud.sql.postgres.SocketFactory could not be instantiated.
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:41)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:129)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.lingk.transformer.provider.impl.GoogleCloudSqlSink.insert(GoogleCloudSqlSink.java:65)
	at io.lingk.transformer.SparkTopologyCreator.handleInsertStatement(SparkTopologyCreator.java:373)
	at io.lingk.transformer.SparkTopologyCreator.main(SparkTopologyCreator.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.sql.postgres.SocketFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:43)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:37)
	... 16 more
```

**Comment by laixer** [comment]
That would indicate that the socket library jar is not on the classpath.

**Comment by kansuke231** [comment]
It seems that SocketFactory.class is in `shaded/guava/cloud/sql/postgres` in a fat jar. Things are working when I specify the class in jdbc url as `socketFactory=shaded.guava.cloud.sql.postgres.SocketFactory`. For the root cause of the original issue, it was due to the lack of postgres dependency in pom.xml so I guess I'm going to close this issue.

Thanks! @laixer

**Comment by laixer** [comment]
Glad you figured it out. Based on the original exception it looks like there *was* a postgres driver on the classpath but it was probably an old version that did not support custom socket factories.

**Comment by irmingard** [comment]
I have downloaded and added [https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/download/v1.0.10/postgres-socket-factory-1.0.10-jar-with-dependencies.jar](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/download/v1.0.10/postgres-socket-factory-1.0.10-jar-with-dependencies.jar) as an additional file to my custom Cloud SQL/PostgreSQL driver and set **socketFactory** to **com.google.cloud.sql.postgres.SocketFactory**. I also added the two dependencies (postgres-socket-factory and postgresql) to my pom file.

When I try to connect to my database, I get

> Connection to [mydatabasename] failed.
> Something unusual has occurred to cause the driver to fail. Please report this exception.

The error message is the same if I remove the **socketFactory** value.

How am I supposed to debug this?

**Comment by kurtisvg** [comment]
@irmingard Would you open a new issue, and include your postgres driver version and JDBC url? Please hide the connection name

**Comment by triesa** [comment]
have same problem with prisma+postgresql in docker-compose

**Comment by smuralimohan** [comment]
GCP sux
