### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request

### ISSUE THREAD

**Issue by carlpett** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#631]
## Bug Description

Trying to connect to a private instance, I'm getting a certificate validation exception. 

## Example code (or command)

I'm loading the socket factory into [Flyway](https://github.com/flyway/flyway), with this connection url:

```
jdbc:postgresql:///db-name?cloudSqlInstance=project-id:region:my-instance&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=true
```

## Stacktrace
```
Caused by: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.SSLExtensions.<init>(Unknown Source)
        at java.base/sun.security.ssl.CertificateRequest$T13CertificateRequestMessage.<init>(Unknown Source)
        at java.base/sun.security.ssl.CertificateRequest$T13CertificateRequestConsumer.consume(Unknown Source)
        at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:304)
        at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:252)
        at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:76)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:223)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        ... 12 more
```

## How to reproduce

  1. Try to connect to private instance

## Environment

1. OS type and version: GCE default Debian 10 image
2. Java SDK version: `openjdk 11.0.2 2019-01-15`
2. Socket Factory version: 1.3.4

**Comment by enocom** [comment]
On a VM with Debian 10, openjdk 11.0.12 2021-07-20, and Socket Factory version 1.3.4, I was able to connect to a private IP instance and query the time without any errors.

Searching for this error, I found someone suggesting that this is a TLS issue. 

Would you mind running with `-Djdk.tls.client.protocols=TLSv1.2` to see if that resolves the issue and reporting back?

https://stackoverflow.com/a/61143833/927514

**Comment by carlpett** [comment]
Downloaded the latest openjdk11 (`OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)`), and yes, there it works. Thanks! I'll see how I can best swap out the flyway-bundled one, but that's quite outside the scope of this issue :) 
Not sure if you want to keep this open to track compatibility doc-wise, otherwise, feel free to close, and thanks for the help!

**Comment by enocom** [comment]
Thanks, @carlpett. I'm going to close this. If there's something we can do better with the socket factory, feel free to re-open.
