### ISSUE TITLE
Unable to connect from IBM WAS liberty using Postgresql connect

### ISSUE THREAD

**Issue by mmouly** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#685]
I'm currently unable to connect to a Google Cloud SQL postgresql database from IBM WAS liberty using the last postgres-socket-factory-1.4.1-jar-with-driver-and-dependencies.jar file.
Following https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-configuring-relational-database-connectivity-in

Here is my liberty datasource : 

       <library id="postgresql-library" filesetRef="postgresql-fileset" />
        <fileset id="postgresql-fileset"  dir="${shared.resource.dir}" includes="postgres-socket-factory-1.4.1-jar-with-driver-and-dependencies.jar" /><dataSource id="jdbc/resdatasource"
                        isolationLevel="TRANSACTION_READ_COMMITTED"
                        jndiName="jdbc/resdatasource"
                        statementCacheSize="150"
                        type="javax.sql.ConnectionPoolDataSource"
                        validationTimeout="0">
                <connectionManager
                        maxPoolSize="25"
                        minPoolSize="10"
                        connectionTimout="10s"
                        agedTimeout="30m" />
                <jdbcDriver libraryRef="postgresql-library"
                        javax.sql.XADataSource="org.postgresql.xa.PGXADataSource"
                        javax.sql.ConnectionPoolDataSource="org.postgresql.ds.PGConnectionPoolDataSource"/>
 
                <properties.postgresql URL="jdbc:postgresql:///postgres"
                        cloudSqlInstance="oceanic-guard-191815:europe-west1:<mydb>"
                        user="postgres"
                        password="postgres"
                        socketFactory="com.google.cloud.sql.postgres.SocketFactory"/>
           </dataSource>

I get the following warning : 
[12/29/21 14:37:35:543 CET] 00000037 JDBCDriverSer W   DSRA8020E: Warning: The property 'cloudSqlInstance' does not exist on the DataSource class org.postgresql.ds.PGConnectionPoolDataSource.

and the stack : 
Caused by: java.sql.SQLException: Something unusual has occurred to cause the driver to fail. Please report this exception. DSRA0010E: SQL State = 99999, Error Code = 0
	at org.postgresql.Driver.connect(Driver.java:286)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
	at org.postgresql.ds.PGConnectionPoolDataSource.getPooledConnection(PGConnectionPoolDataSource.java:58)
	at com.ibm.ws.rsadapter.impl.DatabaseHelper$1.run(DatabaseHelper.java:1514)
	at com.ibm.ws.rsadapter.impl.DatabaseHelper$1.run(DatabaseHelper.java:1500)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:569)
	at com.ibm.ws.rsadapter.impl.DatabaseHelper.getPooledConnection(DatabaseHelper.java:1500)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.getConnection(WSManagedConnectionFactoryImpl.java:853)
	at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.createManagedConnection(WSManagedConnectionFactoryImpl.java:694)
	at com.ibm.ejs.j2c.FreePool.createManagedConnectionWithMCWrapper(FreePool.java:1373)
	at com.ibm.ejs.j2c.FreePool.createOrWaitForConnection(FreePool.java:1247)
	at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:1442)
	at com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:574)
	at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:306)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:140)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:114)
	at ilog.rules.res.persistence.impl.jdbc.IlrDataSourceConnectionProvider.getConnection(IlrDataSourceConnectionProvider.java:143)
	... 37 more
Caused by: java.lang.IllegalArgumentException: cloudSqlInstance property not set. Please specify this property in the JDBC URL or the connection Properties with value in form "project:region:instance"
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:229)
	at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:76)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:226)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:100)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	at org.postgresql.Driver.makeConnection(Driver.java:466)
	at org.postgresql.Driver.connect(Driver.java:265)
	... 57 more

Moving  cloudSqlInstance in the URL from: URL="jdbc:postgresql:///postgres"
to URL="jdbc:postgresql:///postgres?cloudSqlInstance="oceanic-guard-191815:europe-west1:mydb"
has no effect. I get the same stack.

I checked the connection is working fine with squirrel.
Please, can you provide some help ?

**Comment by mmouly** [comment]
closing as I was able to connect by just removing properties and reformating URL as :

`<properties.postgresql URL="jdbc:postgresql://<HOST-IP>/postgres?cloudSqlInstance=oceanic-guard-191815:europe-west1:mydb;socketFactory=com.google.cloud.sql.postgres.SocketFactory" user="postgres" password="postgres"/>`
