### ISSUE TITLE
GraalVM native image test as CI

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#806]
## Feature Description

A test to confirm GraalVM native compilation in this repository in Kokoro.

## Alternatives Considered

GitHub Actions cannot use credentials.

## Additional Context

I'll make the test.

**Comment by suztomo** [comment]
# Failure at jdbc/mysql-j-5

```
[1/7] Initializing...                                                                                    (8.8s @ 0.25GB)
 Version info: 'GraalVM 22.0.0.2 Java 11 CE'
 5 user-provided feature(s)
  - com.google.api.gax.nativeimage.GoogleJsonClientFeature
  - com.google.api.gax.nativeimage.OpenCensusFeature
  - com.google.cloud.sql.nativeimage.CloudSqlFeature
  - com.oracle.svm.thirdparty.gson.GsonFeature
  - org.graalvm.junit.platform.JUnitPlatformFeature
Apr 18, 2022 9:09:51 PM com.google.api.gax.nativeimage.NativeImageUtils registerConstructorsForReflection
WARNING: Failed to find com.mysql.cj.conf.url.SingleConnectionUrl on the classpath for reflection.
Apr 18, 2022 9:09:51 PM com.google.api.gax.nativeimage.NativeImageUtils registerConstructorsForReflection
WARNING: Failed to find com.mysql.cj.log.StandardLogger on the classpath for reflection.

Fatal error: java.lang.NullPointerException
	at com.oracle.svm.hosted.ReachabilityHandlerFeature.registerReachabilityHandler(ReachabilityHandlerFeature.java:97)
	at com.oracle.svm.hosted.ReachabilityHandlerFeature.registerSubtypeReachabilityHandler(ReachabilityHandlerFeature.java:66)
	at com.oracle.svm.hosted.FeatureImpl$BeforeAnalysisAccessImpl.registerSubtypeReachabilityHandler(FeatureImpl.java:424)
	at com.google.cloud.sql.nativeimage.CloudSqlFeature.beforeAnalysis(CloudSqlFeature.java:83)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:695)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:695)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:537)
```

The NPE was thrown at 

```
                throw UserError.abort("registerReachabilityHandler called with an element that is not a Class, Field, Method, or Constructor: %s", trigger.getClass().getTypeName());
```

This means `trigger` was null or `trigger.getClass()` returned null. Even if there isn't NPE, the code would fail with `UserError.abort`.


```
    public void registerSubtypeReachabilityHandler(BeforeAnalysisAccess a, BiConsumer<DuringAnalysisAccess, Class<?>> callback, Class<?> baseClass) {
        registerReachabilityHandler(a, callback, new Class<?>[]{baseClass}, false);
```

**Comment by shubha-rajan** [comment]
Reopening this since we still need to get GraalVM tests working for the other drivers.

**Comment by suztomo** [comment]
I created https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/824 for that.
