### ISSUE TITLE
1.6.0 has affected firebase-admin.

### ISSUE THREAD

**Issue by Saisse** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#851]
## Bug Description

Trying to connect to Firebase with postgres-socket-factory:1.6.0 included in the dependencies yields the error. This problem does not occur in 1.5.0

## Example code (or command)

```scala
// build.sbt
name := "reproduction-project"

libraryDependencies ++= Seq(
//  "com.google.cloud.sql" % "postgres-socket-factory" % "1.5.0", // work
  "com.google.cloud.sql" % "postgres-socket-factory" % "1.6.0", // doesn't work
  "com.google.firebase"  % "firebase-admin"          % "8.1.0",
)
```

```java
// FirebaseConnect.java

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.*;
import java.io.*;
import com.google.firebase.cloud.FirestoreClient;

class FirebaseConnect {
    public FirebaseConnect()  {
        try {
            InputStream stream = new FileInputStream("firebase-service-account.json");
            FirebaseOptions options = FirebaseOptions.builder()
                    .setCredentials(GoogleCredentials.fromStream(stream))
                    .build();
            FirebaseApp.initializeApp(options);
            FirestoreClient.getFirestore();

        } catch (IOException e) {
            throw new RuntimeException("error", e);
        }
    }


    public static void main(String[] args) {
        new FirebaseConnect();
    }
}
```

## Stacktrace
```
[error] com.google.cloud.firestore.FirestoreException: java.lang.IllegalStateException: getTransportChannel() called when needsExecutor() is true
[error]         at com.google.cloud.firestore.FirestoreException.forIOException(FirestoreException.java:94)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:91)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:81)
[error]         at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
[error]         at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:365)
[error]         at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:72)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:72)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:65)
[error]         at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)
[error]         at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
[error]         at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
[error]         at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
[error]         at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
[error]         at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
[error]         at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
[error]         at FirebaseConnect.<init>(FirebaseConnect.java:15)
[error]         at FirebaseConnect.main(FirebaseConnect.java:25)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] Caused by: java.io.IOException: java.lang.IllegalStateException: getTransportChannel() called when needsExecutor() is true
[error]         at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:141)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:89)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:81)
[error]         at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
[error]         at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:365)
[error]         at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:72)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:72)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:65)
[error]         at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)
[error]         at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
[error]         at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
[error]         at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
[error]         at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
[error]         at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
[error]         at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
[error]         at FirebaseConnect.<init>(FirebaseConnect.java:15)
[error]         at FirebaseConnect.main(FirebaseConnect.java:25)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] Caused by: java.lang.IllegalStateException: getTransportChannel() called when needsExecutor() is true
[error]         at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:213)
[error]         at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)
[error]         at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:132)
[error]         at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:126)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:89)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:81)
[error]         at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
[error]         at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:365)
[error]         at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:72)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:72)
[error]         at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:65)
[error]         at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)
[error]         at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
[error]         at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
[error]         at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
[error]         at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
[error]         at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
[error]         at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
[error]         at FirebaseConnect.<init>(FirebaseConnect.java:15)
[error]         at FirebaseConnect.main(FirebaseConnect.java:25)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) com.google.cloud.firestore.FirestoreException: java.lang.IllegalStateException: getTransportChannel() called when needsExecutor() is true

```

## How to reproduce

  1. setup firebase and get  firebase-service-account.json
  2. execute example code with postgres-socket-factory:1.6.0

## Environment

1. OS type and version:  macOS 12.3.1
3. Java SDK version: openjdk 11.0.14 2022-01-18 LTS
2. Socket Factory version: 1.6.0

**Comment by kurtisvg** [comment]
It sounds like you probably have a dependency conflict between the dependencies of the two versions. 

I'm not super familiar with `gradle`, but it looks like you can see a dependency tree with `gradle dependencies`.

**Comment by shubha-rajan** [comment]
+1 to what Kurtis said, looks like a dependency conflict issue.
Since it looks like you're using sbt, you can see the dependency conflicts by adding the following to your `plugins.sbt` file: `addDependencyTreePlugin` (if you're using sbt 1.4+)
`addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")` (older versions)
Then run `sbt dependencyBrowseTree` in the terminal and you'll get a searchable dependency tree in your browser.

**Comment by Saisse** [comment]
Thanks for the reply.
I looked into the suspicious dependencies and found that the error I reported occurs when com.google.api:gax is version 2.0.0 or later, and also without adding postgres-socket-factory as a dependency.

I'll post the error-free configuration in case anyone else encounters the same problem.


```scala
-- build.sbt
name := "reproduction-project"

libraryDependencies ++= Seq(
  "com.google.cloud.sql" % "postgres-socket-factory" % "1.6.0" excludeAll ("com.google.api" % "gax"),
  "com.google.firebase"  % "firebase-admin"          % "8.1.0",
)
```
