### ISSUE TITLE
Brief summary of what bug or error was observed

### ISSUE THREAD

**Issue by safarmer** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#881]
## Bug Description

It looks like the latest release is missing some dependencies. When I update my working Data Grip connection I get an error:

`Driver class 'com.google.common.base.Preconditions' not found.`

## How to reproduce

1. Follow the steps at https://www.jetbrains.com/help/datagrip/connect-to-google-cloud-sql-instances.html#configuring-connections-with-the-cloud-sql-connector-for-java
2. Connect to database

These steps worked fine with v1.5.0 of the socket factory

## Environment

1. OS type and version: Fedora Linux 36
2. Socket Factory version: 1.6.1

**Comment by shubha-rajan** [comment]
Hi @safarmer, thanks for opening this issue! A couple of questions: 
1. Are you using one of the pre-built jars from the releases page, or are you compiling your own jar?
2. Can you provide a full stack trace for the error?

**Comment by safarmer** [comment]
Hi @shubha-rajan, this is with the JAR file downloaded from the releases page. The release artifacts for v1.5.0 also work fine.

[mysql-socket-factory-connector-j-8-1.6.1-jar-with-dependencies.jar](https://storage.googleapis.com/cloud-sql-java-connector/v1.6.1/mysql-socket-factory-connector-j-8-1.6.1-jar-with-dependencies.jar) - BROKEN
[mysql-socket-factory-connector-j-8-1.6.1-jar-with-driver-and-dependencies.jar](https://storage.googleapis.com/cloud-sql-java-connector/v1.6.1/mysql-socket-factory-connector-j-8-1.6.1-jar-with-driver-and-dependencies.jar) - WORKS (with or without the provided JDBC driver from Data Grip on the classpath)

There is no stack trace and the debug logs for Data Grip are included below.

```

2022-06-15 07:27:14,795 [  36057]   INFO - #c.i.e.r.RemoteProcessSupport - Port/ServicesPort/ID: 37696/49620/RemoteDriverImpldadd97ed
2022-06-15 07:27:14,807 [  36069]   INFO - #c.i.e.r.RemoteProcessSupport - 
2022-06-15 07:27:14,882 [  36144]   INFO - #c.i.d.d.DatabaseConnectionEstablisher - Connecting to: jdbc:mysql:///<DATABASE>?cloudSqlInstance=<INSTANCE>
2022-06-15 07:27:14,926 [  36188]   INFO - #c.i.d.d.DatabaseConnectionEstablisher - Auth provider: user-pass
2022-06-15 07:27:14,985 [  36247]   INFO - #c.i.d.d.DatabaseCredentialsAuthProvider - Connecting as: <USER>
2022-06-15 07:27:15,238 [  36500]   WARN - #c.i.d.d.DatabaseConnectionEstablisher - Connecting to: jdbc:mysql:///<DATABASE>?cloudSqlInstance=<INSTANCE>
2022-06-15 07:27:15,239 [  36501]   WARN - #c.i.d.d.DatabaseConnectionEstablisher - com/google/common/base/Preconditions
```

**Comment by safarmer** [comment]
Diffing the two JAR files, it looks like the build is missing more than just the MySQL Connector/J driver in the no-driver download. The diff  shows the `com.google.common`, `com.google.protobuf`, and `com.google.thirdparty` packages are missing from the JAR file with no driver.

I have not used Maven in years, but it looks like the core package is excluding a lot of packages, and the mysql-j-8 package is including them again?

Screenshot of the diff (the command line version was quite noisy):
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/716699/173698335-7942b546-7e5e-4f9a-97e4-58ccb04b09be.png">

**Comment by shubha-rajan** [comment]
I'm going to decrease the priority of this to P1, since for now, reverting to a previous version fixes the issue.

**Comment by kurtisvg** [comment]
We think the problem is related to these exclusions: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/pom.xml#L226-L266

**Comment by hessjcg** [comment]
I have confirmed that there is an java.lang.NoClassDefFoundError when trying to connect via socket factory 1.6.1, and that this does not occur when trying to connect with socket factory 1.6.0. 

Now to try to figure out how to add these dependencies back.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:229)
	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:210)
	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:52)
	at com.google.cloud.sql.mysql.SocketFactory.connect(SocketFactory.java:42)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Main.main(Main.java:11)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Preconditions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more
```
