### ISSUE TITLE
Rate limits lead to flaky tests after moving to Github Actions

### ISSUE THREAD

**Issue by shubha-rajan** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#979]
Note: This error only seems to occur with Postgres IAM tests.
Error message:

```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 429 Too Many Requests
POST https://sqladmin.googleapis.com/sql/v1beta4/projects/***/instances/us-central1~postgres-iam-test:generateEphemeralCert
{
  "code": 429,
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.ErrorInfo",
      "reason": "RATE_LIMIT_EXCEEDED"
    },
    {
      "@type": "type.googleapis.com/google.rpc.Help"
    }
  ],
  "errors": [
    {
      "domain": "global",
      "message": "Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'sqladmin.googleapis.com' for consumer 'project_number:151338197897'.",
      "reason": "rateLimitExceeded"
    }
  ],
  "message": "Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'sqladmin.googleapis.com' for consumer 'project_number:151338197897'.",
  "status": "RESOURCE_EXHAUSTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:439)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.google.cloud.sql.core.CloudSqlInstance.fetchEphemeralCertificate(CloudSqlInstance.java:542)
	... 10 more

```

**Comment by enocom** [comment]
This might be a case of just needing to bump our testing project's API quota. cc @jackwotherspoon who's done this ona  few repos now.

**Comment by jackwotherspoon** [comment]
I have just requested a quota increase from 600 requests per minute per user  to 1200. Hopefully this will resolve or reduce these kind of errors moving forward.

**Comment by jackwotherspoon** [comment]
@shubha-rajan Let me know if you are still seeing rate limit issues and I can look into bumping the quota again if need be.

**Comment by enocom** [comment]
Closing this as it seems we’re doing better now.
